// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: slb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 中奖详情响应
type Slb_BetOrderResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderSn            *string                `protobuf:"bytes,1,opt,name=orderSn,proto3,oneof" json:"orderSn"`                         // 订单号
	Balance            *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance"`                       // 余额
	BaseBet            *float64               `protobuf:"fixed64,3,opt,name=baseBet,proto3,oneof" json:"baseBet"`                       // 基础下注
	BetAmount          *float64               `protobuf:"fixed64,4,opt,name=betAmount,proto3,oneof" json:"betAmount"`                   // 下注金额
	Multiplier         *int64                 `protobuf:"varint,5,opt,name=multiplier,proto3,oneof" json:"multiplier"`                  // 下注倍数
	CurWin             *float64               `protobuf:"fixed64,6,opt,name=curWin,proto3,oneof" json:"curWin"`                         // 本轮赢取
	RoundWin           *float64               `protobuf:"fixed64,7,opt,name=roundWin,proto3,oneof" json:"roundWin"`                     // 本轮总赢取
	TotalWin           *float64               `protobuf:"fixed64,8,opt,name=totalWin,proto3,oneof" json:"totalWin"`                     // 总赢取
	FreeTotalWin       *float64               `protobuf:"fixed64,9,opt,name=freeTotalWin,proto3,oneof" json:"freeTotalWin"`             // 免费局累计赢取
	IsRoundOver        *bool                  `protobuf:"varint,10,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver"`               // 下回合扣钱或者下回合减免费次数
	IsSpinOver         *bool                  `protobuf:"varint,11,opt,name=isSpinOver,proto3,oneof" json:"isSpinOver"`                 // 下回合扣钱
	IsFree             *bool                  `protobuf:"varint,13,opt,name=isFree,proto3,oneof" json:"isFree"`                         // 是否处于免费局
	NewFreeTimes       *int64                 `protobuf:"varint,14,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes"`             // 新增免费次数
	RemainingFreeTimes *int64                 `protobuf:"varint,15,opt,name=remainingFreeTimes,proto3,oneof" json:"remainingFreeTimes"` // 免费次数
	TotalFreeTimes     *int64                 `protobuf:"varint,17,opt,name=totalFreeTimes,proto3,oneof" json:"totalFreeTimes"`         // 已使用免费次数
	Cards              *Board                 `protobuf:"bytes,20,opt,name=cards,proto3" json:"cards"`                                  // 盘面
	GameInfo           *Slb_GameInfo          `protobuf:"bytes,30,opt,name=gameInfo,proto3" json:"gameInfo"`                            // 游戏详情
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Slb_BetOrderResponse) Reset() {
	*x = Slb_BetOrderResponse{}
	mi := &file_slb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slb_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slb_BetOrderResponse) ProtoMessage() {}

func (x *Slb_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slb_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Slb_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_slb_proto_rawDescGZIP(), []int{0}
}

func (x *Slb_BetOrderResponse) GetOrderSn() string {
	if x != nil && x.OrderSn != nil {
		return *x.OrderSn
	}
	return ""
}

func (x *Slb_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetBaseBet() float64 {
	if x != nil && x.BaseBet != nil {
		return *x.BaseBet
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetRoundWin() float64 {
	if x != nil && x.RoundWin != nil {
		return *x.RoundWin
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetFreeTotalWin() float64 {
	if x != nil && x.FreeTotalWin != nil {
		return *x.FreeTotalWin
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Slb_BetOrderResponse) GetIsSpinOver() bool {
	if x != nil && x.IsSpinOver != nil {
		return *x.IsSpinOver
	}
	return false
}

func (x *Slb_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Slb_BetOrderResponse) GetNewFreeTimes() int64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetRemainingFreeTimes() int64 {
	if x != nil && x.RemainingFreeTimes != nil {
		return *x.RemainingFreeTimes
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetTotalFreeTimes() int64 {
	if x != nil && x.TotalFreeTimes != nil {
		return *x.TotalFreeTimes
	}
	return 0
}

func (x *Slb_BetOrderResponse) GetCards() *Board {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Slb_BetOrderResponse) GetGameInfo() *Slb_GameInfo {
	if x != nil {
		return x.GameInfo
	}
	return nil
}

type Slb_GameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *int64                 `protobuf:"varint,1,opt,name=state,proto3,oneof" json:"state"`         // 状态：1 炸糊，2 重转到赢，3 招财进宝
	Multi         *int64                 `protobuf:"varint,2,opt,name=multi,proto3,oneof" json:"multi"`         // 总倍率
	RandMulti     *int64                 `protobuf:"varint,3,opt,name=randMulti,proto3,oneof" json:"randMulti"` // 随机倍率
	WinArr        []*WinResult           `protobuf:"bytes,4,rep,name=winArr,proto3" json:"winArr"`              // 线奖中奖结果列表
	WildPos       []int64                `protobuf:"varint,5,rep,packed,name=wildPos,proto3" json:"wildPos"`    // 百搭符号位置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slb_GameInfo) Reset() {
	*x = Slb_GameInfo{}
	mi := &file_slb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slb_GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slb_GameInfo) ProtoMessage() {}

func (x *Slb_GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slb_GameInfo.ProtoReflect.Descriptor instead.
func (*Slb_GameInfo) Descriptor() ([]byte, []int) {
	return file_slb_proto_rawDescGZIP(), []int{1}
}

func (x *Slb_GameInfo) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Slb_GameInfo) GetMulti() int64 {
	if x != nil && x.Multi != nil {
		return *x.Multi
	}
	return 0
}

func (x *Slb_GameInfo) GetRandMulti() int64 {
	if x != nil && x.RandMulti != nil {
		return *x.RandMulti
	}
	return 0
}

func (x *Slb_GameInfo) GetWinArr() []*WinResult {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Slb_GameInfo) GetWildPos() []int64 {
	if x != nil {
		return x.WildPos
	}
	return nil
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []int64                `protobuf:"varint,1,rep,packed,name=elements,proto3" json:"elements"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_slb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_slb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_slb_proto_rawDescGZIP(), []int{2}
}

func (x *Board) GetElements() []int64 {
	if x != nil {
		return x.Elements
	}
	return nil
}

type WinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *int64                 `protobuf:"varint,1,opt,name=symbol,proto3,oneof" json:"symbol"`         // 符号
	SymbolNum     *int64                 `protobuf:"varint,2,opt,name=symbolNum,proto3,oneof" json:"symbolNum"`   // 数量
	Multiplier    *int64                 `protobuf:"varint,3,opt,name=multiplier,proto3,oneof" json:"multiplier"` // 倍率
	LineNo        *int64                 `protobuf:"varint,4,opt,name=lineNo,proto3,oneof" json:"lineNo"`         // 线序
	Grid          *Board                 `protobuf:"bytes,5,opt,name=grid,proto3" json:"grid"`                    // 牌面
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinResult) Reset() {
	*x = WinResult{}
	mi := &file_slb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinResult) ProtoMessage() {}

func (x *WinResult) ProtoReflect() protoreflect.Message {
	mi := &file_slb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinResult.ProtoReflect.Descriptor instead.
func (*WinResult) Descriptor() ([]byte, []int) {
	return file_slb_proto_rawDescGZIP(), []int{3}
}

func (x *WinResult) GetSymbol() int64 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *WinResult) GetSymbolNum() int64 {
	if x != nil && x.SymbolNum != nil {
		return *x.SymbolNum
	}
	return 0
}

func (x *WinResult) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *WinResult) GetLineNo() int64 {
	if x != nil && x.LineNo != nil {
		return *x.LineNo
	}
	return 0
}

func (x *WinResult) GetGrid() *Board {
	if x != nil {
		return x.Grid
	}
	return nil
}

var File_slb_proto protoreflect.FileDescriptor

const file_slb_proto_rawDesc = "" +
	"\n" +
	"\tslb.proto\x12\x03slb\"\xe4\x06\n" +
	"\x14slb_BetOrderResponse\x12\x1d\n" +
	"\aorderSn\x18\x01 \x01(\tH\x00R\aorderSn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12\x1d\n" +
	"\abaseBet\x18\x03 \x01(\x01H\x02R\abaseBet\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x04 \x01(\x01H\x03R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x05 \x01(\x03H\x04R\n" +
	"multiplier\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x06 \x01(\x01H\x05R\x06curWin\x88\x01\x01\x12\x1f\n" +
	"\broundWin\x18\a \x01(\x01H\x06R\broundWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\b \x01(\x01H\aR\btotalWin\x88\x01\x01\x12'\n" +
	"\ffreeTotalWin\x18\t \x01(\x01H\bR\ffreeTotalWin\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\n" +
	" \x01(\bH\tR\visRoundOver\x88\x01\x01\x12#\n" +
	"\n" +
	"isSpinOver\x18\v \x01(\bH\n" +
	"R\n" +
	"isSpinOver\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\r \x01(\bH\vR\x06isFree\x88\x01\x01\x12'\n" +
	"\fnewFreeTimes\x18\x0e \x01(\x03H\fR\fnewFreeTimes\x88\x01\x01\x123\n" +
	"\x12remainingFreeTimes\x18\x0f \x01(\x03H\rR\x12remainingFreeTimes\x88\x01\x01\x12+\n" +
	"\x0etotalFreeTimes\x18\x11 \x01(\x03H\x0eR\x0etotalFreeTimes\x88\x01\x01\x12 \n" +
	"\x05cards\x18\x14 \x01(\v2\n" +
	".slb.BoardR\x05cards\x12-\n" +
	"\bgameInfo\x18\x1e \x01(\v2\x11.slb.slb_GameInfoR\bgameInfoB\n" +
	"\n" +
	"\b_orderSnB\n" +
	"\n" +
	"\b_balanceB\n" +
	"\n" +
	"\b_baseBetB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_multiplierB\t\n" +
	"\a_curWinB\v\n" +
	"\t_roundWinB\v\n" +
	"\t_totalWinB\x0f\n" +
	"\r_freeTotalWinB\x0e\n" +
	"\f_isRoundOverB\r\n" +
	"\v_isSpinOverB\t\n" +
	"\a_isFreeB\x0f\n" +
	"\r_newFreeTimesB\x15\n" +
	"\x13_remainingFreeTimesB\x11\n" +
	"\x0f_totalFreeTimes\"\xcb\x01\n" +
	"\fslb_GameInfo\x12\x19\n" +
	"\x05state\x18\x01 \x01(\x03H\x00R\x05state\x88\x01\x01\x12\x19\n" +
	"\x05multi\x18\x02 \x01(\x03H\x01R\x05multi\x88\x01\x01\x12!\n" +
	"\trandMulti\x18\x03 \x01(\x03H\x02R\trandMulti\x88\x01\x01\x12&\n" +
	"\x06winArr\x18\x04 \x03(\v2\x0e.slb.WinResultR\x06winArr\x12\x18\n" +
	"\awildPos\x18\x05 \x03(\x03R\awildPosB\b\n" +
	"\x06_stateB\b\n" +
	"\x06_multiB\f\n" +
	"\n" +
	"_randMulti\"#\n" +
	"\x05Board\x12\x1a\n" +
	"\belements\x18\x01 \x03(\x03R\belements\"\xe0\x01\n" +
	"\tWinResult\x12\x1b\n" +
	"\x06symbol\x18\x01 \x01(\x03H\x00R\x06symbol\x88\x01\x01\x12!\n" +
	"\tsymbolNum\x18\x02 \x01(\x03H\x01R\tsymbolNum\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x03H\x02R\n" +
	"multiplier\x88\x01\x01\x12\x1b\n" +
	"\x06lineNo\x18\x04 \x01(\x03H\x03R\x06lineNo\x88\x01\x01\x12\x1e\n" +
	"\x04grid\x18\x05 \x01(\v2\n" +
	".slb.BoardR\x04gridB\t\n" +
	"\a_symbolB\f\n" +
	"\n" +
	"_symbolNumB\r\n" +
	"\v_multiplierB\t\n" +
	"\a_lineNoB\x18Z\x16egame-grpc/game/slb/pbb\x06proto3"

var (
	file_slb_proto_rawDescOnce sync.Once
	file_slb_proto_rawDescData []byte
)

func file_slb_proto_rawDescGZIP() []byte {
	file_slb_proto_rawDescOnce.Do(func() {
		file_slb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slb_proto_rawDesc), len(file_slb_proto_rawDesc)))
	})
	return file_slb_proto_rawDescData
}

var file_slb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_slb_proto_goTypes = []any{
	(*Slb_BetOrderResponse)(nil), // 0: slb.slb_BetOrderResponse
	(*Slb_GameInfo)(nil),         // 1: slb.slb_GameInfo
	(*Board)(nil),                // 2: slb.Board
	(*WinResult)(nil),            // 3: slb.WinResult
}
var file_slb_proto_depIdxs = []int32{
	2, // 0: slb.slb_BetOrderResponse.cards:type_name -> slb.Board
	1, // 1: slb.slb_BetOrderResponse.gameInfo:type_name -> slb.slb_GameInfo
	3, // 2: slb.slb_GameInfo.winArr:type_name -> slb.WinResult
	2, // 3: slb.WinResult.grid:type_name -> slb.Board
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_slb_proto_init() }
func file_slb_proto_init() {
	if File_slb_proto != nil {
		return
	}
	file_slb_proto_msgTypes[0].OneofWrappers = []any{}
	file_slb_proto_msgTypes[1].OneofWrappers = []any{}
	file_slb_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slb_proto_rawDesc), len(file_slb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_slb_proto_goTypes,
		DependencyIndexes: file_slb_proto_depIdxs,
		MessageInfos:      file_slb_proto_msgTypes,
	}.Build()
	File_slb_proto = out.File
	file_slb_proto_goTypes = nil
	file_slb_proto_depIdxs = nil
}
