// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: stress/v1/stress.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StressService_PingReq_FullMethodName             = "/stress.v1.StressService/PingReq"
	StressService_ListGames_FullMethodName           = "/stress.v1.StressService/ListGames"
	StressService_ListTasks_FullMethodName           = "/stress.v1.StressService/ListTasks"
	StressService_CreateTask_FullMethodName          = "/stress.v1.StressService/CreateTask"
	StressService_GetTask_FullMethodName             = "/stress.v1.StressService/GetTask"
	StressService_GetTaskUserIds_FullMethodName      = "/stress.v1.StressService/GetTaskUserIds"
	StressService_DeleteTask_FullMethodName          = "/stress.v1.StressService/DeleteTask"
	StressService_CancelTask_FullMethodName          = "/stress.v1.StressService/CancelTask"
	StressService_GetTaskProgress_FullMethodName     = "/stress.v1.StressService/GetTaskProgress"
	StressService_GetTaskStatistics_FullMethodName   = "/stress.v1.StressService/GetTaskStatistics"
	StressService_GetSystemStatistics_FullMethodName = "/stress.v1.StressService/GetSystemStatistics"
)

// StressServiceClient is the client API for StressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StressServiceClient interface {
	// Sends a greeting
	PingReq(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	// --- 游戏相关 ---
	// 获取游戏列表
	ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error)
	// 获取任务列表
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// 创建压测任务
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	// 获取任务详情
	GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	// 获取任务分配的用户ID列表（单独接口，控制 user_ids 体积）
	GetTaskUserIds(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*GetTaskUserIdsResponse, error)
	// 删除任务
	DeleteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 取消任务
	CancelTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取任务进度
	GetTaskProgress(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*GetTaskProgressResponse, error)
	// 获取任务统计
	GetTaskStatistics(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*GetTaskStatisticsResponse, error)
	// 获取系统统计
	GetSystemStatistics(ctx context.Context, in *GetSystemStatisticsRequest, opts ...grpc.CallOption) (*GetSystemStatisticsResponse, error)
}

type stressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStressServiceClient(cc grpc.ClientConnInterface) StressServiceClient {
	return &stressServiceClient{cc}
}

func (c *stressServiceClient) PingReq(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, StressService_PingReq_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) ListGames(ctx context.Context, in *ListGamesRequest, opts ...grpc.CallOption) (*ListGamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGamesResponse)
	err := c.cc.Invoke(ctx, StressService_ListGames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, StressService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, StressService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) GetTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, StressService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) GetTaskUserIds(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*GetTaskUserIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskUserIdsResponse)
	err := c.cc.Invoke(ctx, StressService_GetTaskUserIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) DeleteTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StressService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) CancelTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StressService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) GetTaskProgress(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*GetTaskProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskProgressResponse)
	err := c.cc.Invoke(ctx, StressService_GetTaskProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) GetTaskStatistics(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*GetTaskStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatisticsResponse)
	err := c.cc.Invoke(ctx, StressService_GetTaskStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stressServiceClient) GetSystemStatistics(ctx context.Context, in *GetSystemStatisticsRequest, opts ...grpc.CallOption) (*GetSystemStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSystemStatisticsResponse)
	err := c.cc.Invoke(ctx, StressService_GetSystemStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StressServiceServer is the server API for StressService service.
// All implementations must embed UnimplementedStressServiceServer
// for forward compatibility.
type StressServiceServer interface {
	// Sends a greeting
	PingReq(context.Context, *PingRequest) (*PingReply, error)
	// --- 游戏相关 ---
	// 获取游戏列表
	ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error)
	// 获取任务列表
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// 创建压测任务
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// 获取任务详情
	GetTask(context.Context, *TaskRequest) (*GetTaskResponse, error)
	// 获取任务分配的用户ID列表（单独接口，控制 user_ids 体积）
	GetTaskUserIds(context.Context, *TaskRequest) (*GetTaskUserIdsResponse, error)
	// 删除任务
	DeleteTask(context.Context, *TaskRequest) (*emptypb.Empty, error)
	// 取消任务
	CancelTask(context.Context, *TaskRequest) (*emptypb.Empty, error)
	// 获取任务进度
	GetTaskProgress(context.Context, *TaskRequest) (*GetTaskProgressResponse, error)
	// 获取任务统计
	GetTaskStatistics(context.Context, *TaskRequest) (*GetTaskStatisticsResponse, error)
	// 获取系统统计
	GetSystemStatistics(context.Context, *GetSystemStatisticsRequest) (*GetSystemStatisticsResponse, error)
	mustEmbedUnimplementedStressServiceServer()
}

// UnimplementedStressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStressServiceServer struct{}

func (UnimplementedStressServiceServer) PingReq(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PingReq not implemented")
}
func (UnimplementedStressServiceServer) ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGames not implemented")
}
func (UnimplementedStressServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedStressServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedStressServiceServer) GetTask(context.Context, *TaskRequest) (*GetTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedStressServiceServer) GetTaskUserIds(context.Context, *TaskRequest) (*GetTaskUserIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskUserIds not implemented")
}
func (UnimplementedStressServiceServer) DeleteTask(context.Context, *TaskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedStressServiceServer) CancelTask(context.Context, *TaskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedStressServiceServer) GetTaskProgress(context.Context, *TaskRequest) (*GetTaskProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskProgress not implemented")
}
func (UnimplementedStressServiceServer) GetTaskStatistics(context.Context, *TaskRequest) (*GetTaskStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatistics not implemented")
}
func (UnimplementedStressServiceServer) GetSystemStatistics(context.Context, *GetSystemStatisticsRequest) (*GetSystemStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStatistics not implemented")
}
func (UnimplementedStressServiceServer) mustEmbedUnimplementedStressServiceServer() {}
func (UnimplementedStressServiceServer) testEmbeddedByValue()                       {}

// UnsafeStressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StressServiceServer will
// result in compilation errors.
type UnsafeStressServiceServer interface {
	mustEmbedUnimplementedStressServiceServer()
}

func RegisterStressServiceServer(s grpc.ServiceRegistrar, srv StressServiceServer) {
	// If the following call panics, it indicates UnimplementedStressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StressService_ServiceDesc, srv)
}

func _StressService_PingReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).PingReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_PingReq_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).PingReq(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_ListGames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).ListGames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_ListGames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).ListGames(ctx, req.(*ListGamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).GetTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_GetTaskUserIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).GetTaskUserIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_GetTaskUserIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).GetTaskUserIds(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).DeleteTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).CancelTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_GetTaskProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).GetTaskProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_GetTaskProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).GetTaskProgress(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_GetTaskStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).GetTaskStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_GetTaskStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).GetTaskStatistics(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StressService_GetSystemStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StressServiceServer).GetSystemStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StressService_GetSystemStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StressServiceServer).GetSystemStatistics(ctx, req.(*GetSystemStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StressService_ServiceDesc is the grpc.ServiceDesc for StressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stress.v1.StressService",
	HandlerType: (*StressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PingReq",
			Handler:    _StressService_PingReq_Handler,
		},
		{
			MethodName: "ListGames",
			Handler:    _StressService_ListGames_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _StressService_ListTasks_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _StressService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _StressService_GetTask_Handler,
		},
		{
			MethodName: "GetTaskUserIds",
			Handler:    _StressService_GetTaskUserIds_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _StressService_DeleteTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _StressService_CancelTask_Handler,
		},
		{
			MethodName: "GetTaskProgress",
			Handler:    _StressService_GetTaskProgress_Handler,
		},
		{
			MethodName: "GetTaskStatistics",
			Handler:    _StressService_GetTaskStatistics_Handler,
		},
		{
			MethodName: "GetSystemStatistics",
			Handler:    _StressService_GetSystemStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stress/v1/stress.proto",
}
