// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: stress/v1/stress.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务状态枚举
type TaskStatus int32

const (
	TaskStatus_TASK_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_PENDING     TaskStatus = 1 // 等待中
	TaskStatus_TASK_RUNNING     TaskStatus = 2 // 运行中
	TaskStatus_TASK_COMPLETED   TaskStatus = 3 // 已完成
	TaskStatus_TASK_FAILED      TaskStatus = 4 // 已失败
	TaskStatus_TASK_CANCELLED   TaskStatus = 5 // 已取消
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_UNSPECIFIED",
		1: "TASK_PENDING",
		2: "TASK_RUNNING",
		3: "TASK_COMPLETED",
		4: "TASK_FAILED",
		5: "TASK_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_UNSPECIFIED": 0,
		"TASK_PENDING":     1,
		"TASK_RUNNING":     2,
		"TASK_COMPLETED":   3,
		"TASK_FAILED":      4,
		"TASK_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_stress_v1_stress_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_stress_v1_stress_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_stress_v1_stress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- 游戏列表 ---
type ListGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{2}
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`  // 游戏列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{3}
}

func (x *ListGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *ListGamesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- 任务列表 ---
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=stress.v1.TaskStatus" json:"status,omitempty"` // 状态过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_UNSPECIFIED
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`  // 任务列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- 创建任务 ---
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"` // 任务描述
	Config        *TaskConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`           // 任务配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetConfig() *TaskConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Task          *Task                  `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"` // 创建后的任务信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTaskResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// --- 任务详情 ---
type TaskInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfoRequest) Reset() {
	*x = TaskInfoRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoRequest) ProtoMessage() {}

func (x *TaskInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoRequest.ProtoReflect.Descriptor instead.
func (*TaskInfoRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{8}
}

func (x *TaskInfoRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Task          *Task                  `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"` // 任务详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskInfoResponse) Reset() {
	*x = TaskInfoResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfoResponse) ProtoMessage() {}

func (x *TaskInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfoResponse.ProtoReflect.Descriptor instead.
func (*TaskInfoResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{9}
}

func (x *TaskInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TaskInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskInfoResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// --- 取消任务 ---
type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{10}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{11}
}

func (x *CancelTaskResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- 删除任务 ---
type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// --- 获取任务结果 ---
type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{13}
}

func (x *RecordRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{14}
}

func (x *RecordResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RecordResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 游戏信息
type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`      // 游戏ID
	GameName      string                 `protobuf:"bytes,2,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"` // 游戏名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`           // 游戏描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_stress_v1_stress_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{15}
}

func (x *Game) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Game) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *Game) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 任务配置
type TaskConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GameId         int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                           // 游戏ID
	MemberCount    int32                  `protobuf:"varint,2,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`            // 用户数量
	TimesPerMember int32                  `protobuf:"varint,3,opt,name=times_per_member,json=timesPerMember,proto3" json:"times_per_member,omitempty"` // 每个用户执行次数
	BetOrder       *BetOrderConfig        `protobuf:"bytes,4,opt,name=bet_order,json=betOrder,proto3" json:"bet_order,omitempty"`                      // 下注配置
	BetBonus       []*BetBonusConfig      `protobuf:"bytes,5,rep,name=bet_bonus,json=betBonus,proto3" json:"bet_bonus,omitempty"`                      // 奖励配置
	ApiUrl         string                 `protobuf:"bytes,6,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`                            // API地址
	LaunchUrl      string                 `protobuf:"bytes,7,opt,name=launch_url,json=launchUrl,proto3" json:"launch_url,omitempty"`                   // 启动地址
	SignRequired   bool                   `protobuf:"varint,8,opt,name=sign_required,json=signRequired,proto3" json:"sign_required,omitempty"`         // 是否需要签名
	Merchant       string                 `protobuf:"bytes,9,opt,name=merchant,proto3" json:"merchant,omitempty"`                                      // 商户名称
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskConfig) Reset() {
	*x = TaskConfig{}
	mi := &file_stress_v1_stress_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskConfig) ProtoMessage() {}

func (x *TaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskConfig.ProtoReflect.Descriptor instead.
func (*TaskConfig) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{16}
}

func (x *TaskConfig) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *TaskConfig) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *TaskConfig) GetTimesPerMember() int32 {
	if x != nil {
		return x.TimesPerMember
	}
	return 0
}

func (x *TaskConfig) GetBetOrder() *BetOrderConfig {
	if x != nil {
		return x.BetOrder
	}
	return nil
}

func (x *TaskConfig) GetBetBonus() []*BetBonusConfig {
	if x != nil {
		return x.BetBonus
	}
	return nil
}

func (x *TaskConfig) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *TaskConfig) GetLaunchUrl() string {
	if x != nil {
		return x.LaunchUrl
	}
	return ""
}

func (x *TaskConfig) GetSignRequired() bool {
	if x != nil {
		return x.SignRequired
	}
	return false
}

func (x *TaskConfig) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

// 下注配置
type BetOrderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseMoney     float64                `protobuf:"fixed64,1,opt,name=base_money,json=baseMoney,proto3" json:"base_money,omitempty"` // 基础金额
	Multiple      int64                  `protobuf:"varint,2,opt,name=multiple,proto3" json:"multiple,omitempty"`                     // 倍数
	Purchase      int64                  `protobuf:"varint,3,opt,name=purchase,proto3" json:"purchase,omitempty"`                     // 购买次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetOrderConfig) Reset() {
	*x = BetOrderConfig{}
	mi := &file_stress_v1_stress_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetOrderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetOrderConfig) ProtoMessage() {}

func (x *BetOrderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetOrderConfig.ProtoReflect.Descriptor instead.
func (*BetOrderConfig) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{17}
}

func (x *BetOrderConfig) GetBaseMoney() float64 {
	if x != nil {
		return x.BaseMoney
	}
	return 0
}

func (x *BetOrderConfig) GetMultiple() int64 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

func (x *BetOrderConfig) GetPurchase() int64 {
	if x != nil {
		return x.Purchase
	}
	return 0
}

// 奖励配置
type BetBonusConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                             // 游戏ID
	BonusNum      int64                  `protobuf:"varint,2,opt,name=bonus_num,json=bonusNum,proto3" json:"bonus_num,omitempty"`                       // 指定奖励编号（0表示随机）
	RandomNums    []int64                `protobuf:"varint,3,rep,packed,name=random_nums,json=randomNums,proto3" json:"random_nums,omitempty"`          // 随机范围 [min, max]
	BonusSequence []int64                `protobuf:"varint,4,rep,packed,name=bonus_sequence,json=bonusSequence,proto3" json:"bonus_sequence,omitempty"` // 奖励序列
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetBonusConfig) Reset() {
	*x = BetBonusConfig{}
	mi := &file_stress_v1_stress_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetBonusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetBonusConfig) ProtoMessage() {}

func (x *BetBonusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetBonusConfig.ProtoReflect.Descriptor instead.
func (*BetBonusConfig) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{18}
}

func (x *BetBonusConfig) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *BetBonusConfig) GetBonusNum() int64 {
	if x != nil {
		return x.BonusNum
	}
	return 0
}

func (x *BetBonusConfig) GetRandomNums() []int64 {
	if x != nil {
		return x.RandomNums
	}
	return nil
}

func (x *BetBonusConfig) GetBonusSequence() []int64 {
	if x != nil {
		return x.BonusSequence
	}
	return nil
}

// 任务完整信息
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`              // 任务ID
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=stress.v1.TaskStatus" json:"status,omitempty"` // 任务状态
	Config        *TaskConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`                            // 任务配置
	RecordUrl     string                 `protobuf:"bytes,5,opt,name=record_url,json=recordUrl,proto3" json:"record_url,omitempty"`     // 任务结果地址
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`     // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`     // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_stress_v1_stress_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{19}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_UNSPECIFIED
}

func (x *Task) GetConfig() *TaskConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Task) GetRecordUrl() string {
	if x != nil {
		return x.RecordUrl
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 任务完成/统计报告（供 Prometheus、飞书通知、API 统一复用）
type TaskCompletionReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                        // 任务ID
	GameId        int64                  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                       // 游戏ID
	Process       int64                  `protobuf:"varint,3,opt,name=process,proto3" json:"process,omitempty"`                                   // 已完成局数
	Target        int64                  `protobuf:"varint,4,opt,name=target,proto3" json:"target,omitempty"`                                     // 目标局数
	Step          int64                  `protobuf:"varint,5,opt,name=step,proto3" json:"step,omitempty"`                                         // 总步数
	Duration      string                 `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`                                  // 耗时（格式化，如 1.5h）
	Qps           float64                `protobuf:"fixed64,7,opt,name=qps,proto3" json:"qps,omitempty"`                                          // QPS
	AvgLatency    string                 `protobuf:"bytes,8,opt,name=avg_latency,json=avgLatency,proto3" json:"avg_latency,omitempty"`            // 平均延迟（格式化，如 12.34ms）
	OrderCount    int64                  `protobuf:"varint,9,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`           // 订单数
	TotalBet      int64                  `protobuf:"varint,10,opt,name=total_bet,json=totalBet,proto3" json:"total_bet,omitempty"`                // 总下注（×1e4）
	TotalWin      int64                  `protobuf:"varint,11,opt,name=total_win,json=totalWin,proto3" json:"total_win,omitempty"`                // 总赢（×1e4）
	RtpPct        float64                `protobuf:"fixed64,12,opt,name=rtp_pct,json=rtpPct,proto3" json:"rtp_pct,omitempty"`                     // RTP %
	ActiveMembers int64                  `protobuf:"varint,13,opt,name=active_members,json=activeMembers,proto3" json:"active_members,omitempty"` // 活跃成员数（运行中）
	Completed     int64                  `protobuf:"varint,14,opt,name=completed,proto3" json:"completed,omitempty"`                              // 完成成员数
	Failed        int64                  `protobuf:"varint,15,opt,name=failed,proto3" json:"failed,omitempty"`                                    // 失败成员数
	FailedReqs    int64                  `protobuf:"varint,16,opt,name=failed_reqs,json=failedReqs,proto3" json:"failed_reqs,omitempty"`          // 失败请求数
	ProgressPct   float64                `protobuf:"fixed64,17,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`      // 进度 % (process/target*100, 上限 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletionReport) Reset() {
	*x = TaskCompletionReport{}
	mi := &file_stress_v1_stress_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletionReport) ProtoMessage() {}

func (x *TaskCompletionReport) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletionReport.ProtoReflect.Descriptor instead.
func (*TaskCompletionReport) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{20}
}

func (x *TaskCompletionReport) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompletionReport) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *TaskCompletionReport) GetProcess() int64 {
	if x != nil {
		return x.Process
	}
	return 0
}

func (x *TaskCompletionReport) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *TaskCompletionReport) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *TaskCompletionReport) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TaskCompletionReport) GetQps() float64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *TaskCompletionReport) GetAvgLatency() string {
	if x != nil {
		return x.AvgLatency
	}
	return ""
}

func (x *TaskCompletionReport) GetOrderCount() int64 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *TaskCompletionReport) GetTotalBet() int64 {
	if x != nil {
		return x.TotalBet
	}
	return 0
}

func (x *TaskCompletionReport) GetTotalWin() int64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *TaskCompletionReport) GetRtpPct() float64 {
	if x != nil {
		return x.RtpPct
	}
	return 0
}

func (x *TaskCompletionReport) GetActiveMembers() int64 {
	if x != nil {
		return x.ActiveMembers
	}
	return 0
}

func (x *TaskCompletionReport) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *TaskCompletionReport) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *TaskCompletionReport) GetFailedReqs() int64 {
	if x != nil {
		return x.FailedReqs
	}
	return 0
}

func (x *TaskCompletionReport) GetProgressPct() float64 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

var File_stress_v1_stress_proto protoreflect.FileDescriptor

const file_stress_v1_stress_proto_rawDesc = "" +
	"\n" +
	"\x16stress/v1/stress.proto\x12\tstress.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\tPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10ListGamesRequest\"P\n" +
	"\x11ListGamesResponse\x12%\n" +
	"\x05games\x18\x01 \x03(\v2\x0f.stress.v1.GameR\x05games\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"A\n" +
	"\x10ListTasksRequest\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.stress.v1.TaskStatusR\x06status\"P\n" +
	"\x11ListTasksResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.stress.v1.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"n\n" +
	"\x11CreateTaskRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x127\n" +
	"\x06config\x18\x02 \x01(\v2\x15.stress.v1.TaskConfigB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06config\"g\n" +
	"\x12CreateTaskResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04task\x18\x03 \x01(\v2\x0f.stress.v1.TaskR\x04task\"3\n" +
	"\x0fTaskInfoRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\"e\n" +
	"\x10TaskInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\x04task\x18\x03 \x01(\v2\x0f.stress.v1.TaskR\x04task\"5\n" +
	"\x11CancelTaskRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\"B\n" +
	"\x12CancelTaskResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"5\n" +
	"\x11DeleteTaskRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\"1\n" +
	"\rRecordRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\"P\n" +
	"\x0eRecordResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"^\n" +
	"\x04Game\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\x12\x1b\n" +
	"\tgame_name\x18\x02 \x01(\tR\bgameName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8e\x03\n" +
	"\n" +
	"TaskConfig\x12 \n" +
	"\agame_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06gameId\x12-\n" +
	"\fmember_count\x18\x02 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90N(\x01R\vmemberCount\x124\n" +
	"\x10times_per_member\x18\x03 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90N(\x01R\x0etimesPerMember\x126\n" +
	"\tbet_order\x18\x04 \x01(\v2\x19.stress.v1.BetOrderConfigR\bbetOrder\x126\n" +
	"\tbet_bonus\x18\x05 \x03(\v2\x19.stress.v1.BetBonusConfigR\bbetBonus\x12 \n" +
	"\aapi_url\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06apiUrl\x12&\n" +
	"\n" +
	"launch_url\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tlaunchUrl\x12#\n" +
	"\rsign_required\x18\b \x01(\bR\fsignRequired\x12\x1a\n" +
	"\bmerchant\x18\t \x01(\tR\bmerchant\"\x89\x01\n" +
	"\x0eBetOrderConfig\x12-\n" +
	"\n" +
	"base_money\x18\x01 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\tbaseMoney\x12#\n" +
	"\bmultiple\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bmultiple\x12#\n" +
	"\bpurchase\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\bpurchase\"\x97\x01\n" +
	"\x0eBetBonusConfig\x12 \n" +
	"\agame_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06gameId\x12\x1b\n" +
	"\tbonus_num\x18\x02 \x01(\x03R\bbonusNum\x12\x1f\n" +
	"\vrandom_nums\x18\x03 \x03(\x03R\n" +
	"randomNums\x12%\n" +
	"\x0ebonus_sequence\x18\x04 \x03(\x03R\rbonusSequence\"\x92\x02\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.stress.v1.TaskStatusR\x06status\x12-\n" +
	"\x06config\x18\x04 \x01(\v2\x15.stress.v1.TaskConfigR\x06config\x12\x1d\n" +
	"\n" +
	"record_url\x18\x05 \x01(\tR\trecordUrl\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf2\x03\n" +
	"\x14TaskCompletionReport\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x03R\x06gameId\x12\x18\n" +
	"\aprocess\x18\x03 \x01(\x03R\aprocess\x12\x16\n" +
	"\x06target\x18\x04 \x01(\x03R\x06target\x12\x12\n" +
	"\x04step\x18\x05 \x01(\x03R\x04step\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\tR\bduration\x12\x10\n" +
	"\x03qps\x18\a \x01(\x01R\x03qps\x12\x1f\n" +
	"\vavg_latency\x18\b \x01(\tR\n" +
	"avgLatency\x12\x1f\n" +
	"\vorder_count\x18\t \x01(\x03R\n" +
	"orderCount\x12\x1b\n" +
	"\ttotal_bet\x18\n" +
	" \x01(\x03R\btotalBet\x12\x1b\n" +
	"\ttotal_win\x18\v \x01(\x03R\btotalWin\x12\x17\n" +
	"\artp_pct\x18\f \x01(\x01R\x06rtpPct\x12%\n" +
	"\x0eactive_members\x18\r \x01(\x03R\ractiveMembers\x12\x1c\n" +
	"\tcompleted\x18\x0e \x01(\x03R\tcompleted\x12\x16\n" +
	"\x06failed\x18\x0f \x01(\x03R\x06failed\x12\x1f\n" +
	"\vfailed_reqs\x18\x10 \x01(\x03R\n" +
	"failedReqs\x12!\n" +
	"\fprogress_pct\x18\x11 \x01(\x01R\vprogressPct*\x7f\n" +
	"\n" +
	"TaskStatus\x12\x14\n" +
	"\x10TASK_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTASK_PENDING\x10\x01\x12\x10\n" +
	"\fTASK_RUNNING\x10\x02\x12\x12\n" +
	"\x0eTASK_COMPLETED\x10\x03\x12\x0f\n" +
	"\vTASK_FAILED\x10\x04\x12\x12\n" +
	"\x0eTASK_CANCELLED\x10\x052\xc7\x06\n" +
	"\rStressService\x12T\n" +
	"\aPingReq\x12\x16.stress.v1.PingRequest\x1a\x14.stress.v1.PingReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/stress/ping/{name}\x12a\n" +
	"\tListGames\x12\x1b.stress.v1.ListGamesRequest\x1a\x1c.stress.v1.ListGamesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/stress/ListGames\x12a\n" +
	"\tListTasks\x12\x1b.stress.v1.ListTasksRequest\x1a\x1c.stress.v1.ListTasksResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/stress/ListTasks\x12h\n" +
	"\n" +
	"CreateTask\x12\x1c.stress.v1.CreateTaskRequest\x1a\x1d.stress.v1.CreateTaskResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/stress/CreateTask\x12g\n" +
	"\bTaskInfo\x12\x1a.stress.v1.TaskInfoRequest\x1a\x1b.stress.v1.TaskInfoResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/stress/TaskInfo/{task_id}\x12h\n" +
	"\n" +
	"DeleteTask\x12\x1c.stress.v1.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/stress/DeleteTask/{task_id}\x12r\n" +
	"\n" +
	"CancelTask\x12\x1c.stress.v1.CancelTaskRequest\x1a\x1d.stress.v1.CancelTaskResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/stress/CancelTask/{task_id}\x12i\n" +
	"\tGetRecord\x12\x18.stress.v1.RecordRequest\x1a\x19.stress.v1.RecordResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/stress/TaskRecord/{task_id}B\x19Z\x17stress/api/stress/v1;v1b\x06proto3"

var (
	file_stress_v1_stress_proto_rawDescOnce sync.Once
	file_stress_v1_stress_proto_rawDescData []byte
)

func file_stress_v1_stress_proto_rawDescGZIP() []byte {
	file_stress_v1_stress_proto_rawDescOnce.Do(func() {
		file_stress_v1_stress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stress_v1_stress_proto_rawDesc), len(file_stress_v1_stress_proto_rawDesc)))
	})
	return file_stress_v1_stress_proto_rawDescData
}

var file_stress_v1_stress_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stress_v1_stress_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_stress_v1_stress_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: stress.v1.TaskStatus
	(*PingRequest)(nil),           // 1: stress.v1.PingRequest
	(*PingReply)(nil),             // 2: stress.v1.PingReply
	(*ListGamesRequest)(nil),      // 3: stress.v1.ListGamesRequest
	(*ListGamesResponse)(nil),     // 4: stress.v1.ListGamesResponse
	(*ListTasksRequest)(nil),      // 5: stress.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 6: stress.v1.ListTasksResponse
	(*CreateTaskRequest)(nil),     // 7: stress.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 8: stress.v1.CreateTaskResponse
	(*TaskInfoRequest)(nil),       // 9: stress.v1.TaskInfoRequest
	(*TaskInfoResponse)(nil),      // 10: stress.v1.TaskInfoResponse
	(*CancelTaskRequest)(nil),     // 11: stress.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 12: stress.v1.CancelTaskResponse
	(*DeleteTaskRequest)(nil),     // 13: stress.v1.DeleteTaskRequest
	(*RecordRequest)(nil),         // 14: stress.v1.RecordRequest
	(*RecordResponse)(nil),        // 15: stress.v1.RecordResponse
	(*Game)(nil),                  // 16: stress.v1.Game
	(*TaskConfig)(nil),            // 17: stress.v1.TaskConfig
	(*BetOrderConfig)(nil),        // 18: stress.v1.BetOrderConfig
	(*BetBonusConfig)(nil),        // 19: stress.v1.BetBonusConfig
	(*Task)(nil),                  // 20: stress.v1.Task
	(*TaskCompletionReport)(nil),  // 21: stress.v1.TaskCompletionReport
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 23: google.protobuf.Empty
}
var file_stress_v1_stress_proto_depIdxs = []int32{
	16, // 0: stress.v1.ListGamesResponse.games:type_name -> stress.v1.Game
	0,  // 1: stress.v1.ListTasksRequest.status:type_name -> stress.v1.TaskStatus
	20, // 2: stress.v1.ListTasksResponse.tasks:type_name -> stress.v1.Task
	17, // 3: stress.v1.CreateTaskRequest.config:type_name -> stress.v1.TaskConfig
	20, // 4: stress.v1.CreateTaskResponse.task:type_name -> stress.v1.Task
	20, // 5: stress.v1.TaskInfoResponse.task:type_name -> stress.v1.Task
	18, // 6: stress.v1.TaskConfig.bet_order:type_name -> stress.v1.BetOrderConfig
	19, // 7: stress.v1.TaskConfig.bet_bonus:type_name -> stress.v1.BetBonusConfig
	0,  // 8: stress.v1.Task.status:type_name -> stress.v1.TaskStatus
	17, // 9: stress.v1.Task.config:type_name -> stress.v1.TaskConfig
	22, // 10: stress.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	22, // 11: stress.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 12: stress.v1.StressService.PingReq:input_type -> stress.v1.PingRequest
	3,  // 13: stress.v1.StressService.ListGames:input_type -> stress.v1.ListGamesRequest
	5,  // 14: stress.v1.StressService.ListTasks:input_type -> stress.v1.ListTasksRequest
	7,  // 15: stress.v1.StressService.CreateTask:input_type -> stress.v1.CreateTaskRequest
	9,  // 16: stress.v1.StressService.TaskInfo:input_type -> stress.v1.TaskInfoRequest
	13, // 17: stress.v1.StressService.DeleteTask:input_type -> stress.v1.DeleteTaskRequest
	11, // 18: stress.v1.StressService.CancelTask:input_type -> stress.v1.CancelTaskRequest
	14, // 19: stress.v1.StressService.GetRecord:input_type -> stress.v1.RecordRequest
	2,  // 20: stress.v1.StressService.PingReq:output_type -> stress.v1.PingReply
	4,  // 21: stress.v1.StressService.ListGames:output_type -> stress.v1.ListGamesResponse
	6,  // 22: stress.v1.StressService.ListTasks:output_type -> stress.v1.ListTasksResponse
	8,  // 23: stress.v1.StressService.CreateTask:output_type -> stress.v1.CreateTaskResponse
	10, // 24: stress.v1.StressService.TaskInfo:output_type -> stress.v1.TaskInfoResponse
	23, // 25: stress.v1.StressService.DeleteTask:output_type -> google.protobuf.Empty
	12, // 26: stress.v1.StressService.CancelTask:output_type -> stress.v1.CancelTaskResponse
	15, // 27: stress.v1.StressService.GetRecord:output_type -> stress.v1.RecordResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_stress_v1_stress_proto_init() }
func file_stress_v1_stress_proto_init() {
	if File_stress_v1_stress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stress_v1_stress_proto_rawDesc), len(file_stress_v1_stress_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stress_v1_stress_proto_goTypes,
		DependencyIndexes: file_stress_v1_stress_proto_depIdxs,
		EnumInfos:         file_stress_v1_stress_proto_enumTypes,
		MessageInfos:      file_stress_v1_stress_proto_msgTypes,
	}.Build()
	File_stress_v1_stress_proto = out.File
	file_stress_v1_stress_proto_goTypes = nil
	file_stress_v1_stress_proto_depIdxs = nil
}
