// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.1
// source: stress/v1/stress.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationStressServiceCancelTask = "/stress.v1.StressService/CancelTask"
const OperationStressServiceCreateTask = "/stress.v1.StressService/CreateTask"
const OperationStressServiceDeleteTask = "/stress.v1.StressService/DeleteTask"
const OperationStressServiceGetSystemStatistics = "/stress.v1.StressService/GetSystemStatistics"
const OperationStressServiceGetTask = "/stress.v1.StressService/GetTask"
const OperationStressServiceGetTaskProgress = "/stress.v1.StressService/GetTaskProgress"
const OperationStressServiceGetTaskStatistics = "/stress.v1.StressService/GetTaskStatistics"
const OperationStressServiceGetTaskUserIds = "/stress.v1.StressService/GetTaskUserIds"
const OperationStressServiceListGames = "/stress.v1.StressService/ListGames"
const OperationStressServiceListTasks = "/stress.v1.StressService/ListTasks"
const OperationStressServicePingReq = "/stress.v1.StressService/PingReq"

type StressServiceHTTPServer interface {
	// CancelTask 取消任务
	CancelTask(context.Context, *TaskRequest) (*emptypb.Empty, error)
	// CreateTask 创建压测任务
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// DeleteTask 删除任务
	DeleteTask(context.Context, *TaskRequest) (*emptypb.Empty, error)
	// GetSystemStatistics 获取系统统计
	GetSystemStatistics(context.Context, *GetSystemStatisticsRequest) (*GetSystemStatisticsResponse, error)
	// GetTask 获取任务详情
	GetTask(context.Context, *TaskRequest) (*GetTaskResponse, error)
	// GetTaskProgress 获取任务进度
	GetTaskProgress(context.Context, *TaskRequest) (*GetTaskProgressResponse, error)
	// GetTaskStatistics 获取任务统计
	GetTaskStatistics(context.Context, *TaskRequest) (*GetTaskStatisticsResponse, error)
	// GetTaskUserIds 获取任务分配的用户ID列表（单独接口，控制 user_ids 体积）
	GetTaskUserIds(context.Context, *TaskRequest) (*GetTaskUserIdsResponse, error)
	// ListGames --- 游戏相关 ---
	// 获取游戏列表
	ListGames(context.Context, *ListGamesRequest) (*ListGamesResponse, error)
	// ListTasks 获取任务列表
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// PingReq Sends a greeting
	PingReq(context.Context, *PingRequest) (*PingReply, error)
}

func RegisterStressServiceHTTPServer(s *http.Server, srv StressServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/stress/ping/{name}", _StressService_PingReq0_HTTP_Handler(srv))
	r.GET("/stress/ListGames", _StressService_ListGames0_HTTP_Handler(srv))
	r.GET("/stress/ListTasks", _StressService_ListTasks0_HTTP_Handler(srv))
	r.POST("/stress/CreateTask", _StressService_CreateTask0_HTTP_Handler(srv))
	r.GET("/stress/GetTask/{task_id}", _StressService_GetTask0_HTTP_Handler(srv))
	r.GET("/stress/GetTaskUserIds/{task_id}/user_ids", _StressService_GetTaskUserIds0_HTTP_Handler(srv))
	r.DELETE("/stress/DeleteTask/{task_id}", _StressService_DeleteTask0_HTTP_Handler(srv))
	r.POST("/stress/CancelTask/{task_id}", _StressService_CancelTask0_HTTP_Handler(srv))
	r.GET("/stress/GetTaskProgress/{task_id}", _StressService_GetTaskProgress0_HTTP_Handler(srv))
	r.GET("/stress/GetTaskStatistics/{task_id}", _StressService_GetTaskStatistics0_HTTP_Handler(srv))
	r.GET("/stress/statistics", _StressService_GetSystemStatistics0_HTTP_Handler(srv))
}

func _StressService_PingReq0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServicePingReq)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PingReq(ctx, req.(*PingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingReply)
		return ctx.Result(200, reply)
	}
}

func _StressService_ListGames0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGamesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceListGames)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGames(ctx, req.(*ListGamesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGamesResponse)
		return ctx.Result(200, reply)
	}
}

func _StressService_ListTasks0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*ListTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksResponse)
		return ctx.Result(200, reply)
	}
}

func _StressService_CreateTask0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceCreateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTask(ctx, req.(*CreateTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTaskResponse)
		return ctx.Result(200, reply)
	}
}

func _StressService_GetTask0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceGetTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTask(ctx, req.(*TaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskResponse)
		return ctx.Result(200, reply)
	}
}

func _StressService_GetTaskUserIds0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceGetTaskUserIds)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskUserIds(ctx, req.(*TaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskUserIdsResponse)
		return ctx.Result(200, reply)
	}
}

func _StressService_DeleteTask0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceDeleteTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTask(ctx, req.(*TaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _StressService_CancelTask0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceCancelTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelTask(ctx, req.(*TaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _StressService_GetTaskProgress0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceGetTaskProgress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskProgress(ctx, req.(*TaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskProgressResponse)
		return ctx.Result(200, reply)
	}
}

func _StressService_GetTaskStatistics0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceGetTaskStatistics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskStatistics(ctx, req.(*TaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskStatisticsResponse)
		return ctx.Result(200, reply)
	}
}

func _StressService_GetSystemStatistics0_HTTP_Handler(srv StressServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSystemStatisticsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationStressServiceGetSystemStatistics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSystemStatistics(ctx, req.(*GetSystemStatisticsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSystemStatisticsResponse)
		return ctx.Result(200, reply)
	}
}

type StressServiceHTTPClient interface {
	// CancelTask 取消任务
	CancelTask(ctx context.Context, req *TaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// CreateTask 创建压测任务
	CreateTask(ctx context.Context, req *CreateTaskRequest, opts ...http.CallOption) (rsp *CreateTaskResponse, err error)
	// DeleteTask 删除任务
	DeleteTask(ctx context.Context, req *TaskRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetSystemStatistics 获取系统统计
	GetSystemStatistics(ctx context.Context, req *GetSystemStatisticsRequest, opts ...http.CallOption) (rsp *GetSystemStatisticsResponse, err error)
	// GetTask 获取任务详情
	GetTask(ctx context.Context, req *TaskRequest, opts ...http.CallOption) (rsp *GetTaskResponse, err error)
	// GetTaskProgress 获取任务进度
	GetTaskProgress(ctx context.Context, req *TaskRequest, opts ...http.CallOption) (rsp *GetTaskProgressResponse, err error)
	// GetTaskStatistics 获取任务统计
	GetTaskStatistics(ctx context.Context, req *TaskRequest, opts ...http.CallOption) (rsp *GetTaskStatisticsResponse, err error)
	// GetTaskUserIds 获取任务分配的用户ID列表（单独接口，控制 user_ids 体积）
	GetTaskUserIds(ctx context.Context, req *TaskRequest, opts ...http.CallOption) (rsp *GetTaskUserIdsResponse, err error)
	// ListGames --- 游戏相关 ---
	// 获取游戏列表
	ListGames(ctx context.Context, req *ListGamesRequest, opts ...http.CallOption) (rsp *ListGamesResponse, err error)
	// ListTasks 获取任务列表
	ListTasks(ctx context.Context, req *ListTasksRequest, opts ...http.CallOption) (rsp *ListTasksResponse, err error)
	// PingReq Sends a greeting
	PingReq(ctx context.Context, req *PingRequest, opts ...http.CallOption) (rsp *PingReply, err error)
}

type StressServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewStressServiceHTTPClient(client *http.Client) StressServiceHTTPClient {
	return &StressServiceHTTPClientImpl{client}
}

// CancelTask 取消任务
func (c *StressServiceHTTPClientImpl) CancelTask(ctx context.Context, in *TaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/stress/CancelTask/{task_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStressServiceCancelTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTask 创建压测任务
func (c *StressServiceHTTPClientImpl) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...http.CallOption) (*CreateTaskResponse, error) {
	var out CreateTaskResponse
	pattern := "/stress/CreateTask"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationStressServiceCreateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTask 删除任务
func (c *StressServiceHTTPClientImpl) DeleteTask(ctx context.Context, in *TaskRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/stress/DeleteTask/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServiceDeleteTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSystemStatistics 获取系统统计
func (c *StressServiceHTTPClientImpl) GetSystemStatistics(ctx context.Context, in *GetSystemStatisticsRequest, opts ...http.CallOption) (*GetSystemStatisticsResponse, error) {
	var out GetSystemStatisticsResponse
	pattern := "/stress/statistics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServiceGetSystemStatistics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTask 获取任务详情
func (c *StressServiceHTTPClientImpl) GetTask(ctx context.Context, in *TaskRequest, opts ...http.CallOption) (*GetTaskResponse, error) {
	var out GetTaskResponse
	pattern := "/stress/GetTask/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServiceGetTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskProgress 获取任务进度
func (c *StressServiceHTTPClientImpl) GetTaskProgress(ctx context.Context, in *TaskRequest, opts ...http.CallOption) (*GetTaskProgressResponse, error) {
	var out GetTaskProgressResponse
	pattern := "/stress/GetTaskProgress/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServiceGetTaskProgress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskStatistics 获取任务统计
func (c *StressServiceHTTPClientImpl) GetTaskStatistics(ctx context.Context, in *TaskRequest, opts ...http.CallOption) (*GetTaskStatisticsResponse, error) {
	var out GetTaskStatisticsResponse
	pattern := "/stress/GetTaskStatistics/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServiceGetTaskStatistics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskUserIds 获取任务分配的用户ID列表（单独接口，控制 user_ids 体积）
func (c *StressServiceHTTPClientImpl) GetTaskUserIds(ctx context.Context, in *TaskRequest, opts ...http.CallOption) (*GetTaskUserIdsResponse, error) {
	var out GetTaskUserIdsResponse
	pattern := "/stress/GetTaskUserIds/{task_id}/user_ids"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServiceGetTaskUserIds))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListGames --- 游戏相关 ---
// 获取游戏列表
func (c *StressServiceHTTPClientImpl) ListGames(ctx context.Context, in *ListGamesRequest, opts ...http.CallOption) (*ListGamesResponse, error) {
	var out ListGamesResponse
	pattern := "/stress/ListGames"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServiceListGames))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTasks 获取任务列表
func (c *StressServiceHTTPClientImpl) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...http.CallOption) (*ListTasksResponse, error) {
	var out ListTasksResponse
	pattern := "/stress/ListTasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServiceListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PingReq Sends a greeting
func (c *StressServiceHTTPClientImpl) PingReq(ctx context.Context, in *PingRequest, opts ...http.CallOption) (*PingReply, error) {
	var out PingReply
	pattern := "/stress/ping/{name}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationStressServicePingReq))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
