// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: stress/v1/stress.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务状态枚举
type TaskStatus int32

const (
	TaskStatus_TASK_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_PENDING     TaskStatus = 1 // 等待中
	TaskStatus_TASK_RUNNING     TaskStatus = 2 // 运行中
	TaskStatus_TASK_COMPLETED   TaskStatus = 3 // 已完成
	TaskStatus_TASK_FAILED      TaskStatus = 4 // 已失败
	TaskStatus_TASK_CANCELLED   TaskStatus = 5 // 已取消
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_UNSPECIFIED",
		1: "TASK_PENDING",
		2: "TASK_RUNNING",
		3: "TASK_COMPLETED",
		4: "TASK_FAILED",
		5: "TASK_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_UNSPECIFIED": 0,
		"TASK_PENDING":     1,
		"TASK_RUNNING":     2,
		"TASK_COMPLETED":   3,
		"TASK_FAILED":      4,
		"TASK_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_stress_v1_stress_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_stress_v1_stress_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_stress_v1_stress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- 游戏列表 ---
type ListGamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{2}
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`  // 游戏列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{3}
}

func (x *ListGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *ListGamesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- 创建任务 ---
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"` // 任务描述
	Config        *TaskConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`           // 任务配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetConfig() *TaskConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // 创建后的任务信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// --- 任务详情 ---
type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{6}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // 任务详情
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// --- 任务列表 ---
type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=stress.v1.TaskStatus" json:"status,omitempty"` // 状态过滤
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`                            // 其他过滤条件
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{8}
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_UNSPECIFIED
}

func (x *ListTasksRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`  // 任务列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{9}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- 任务用户ID ---
type GetTaskUserIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 分配的用户ID列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                           // 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskUserIdsResponse) Reset() {
	*x = GetTaskUserIdsResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskUserIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskUserIdsResponse) ProtoMessage() {}

func (x *GetTaskUserIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskUserIdsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskUserIdsResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskUserIdsResponse) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetTaskUserIdsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// --- 任务进度统计 ---
type GetTaskProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *TaskProgress          `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"` // 任务进度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskProgressResponse) Reset() {
	*x = GetTaskProgressResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskProgressResponse) ProtoMessage() {}

func (x *GetTaskProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskProgressResponse.ProtoReflect.Descriptor instead.
func (*GetTaskProgressResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskProgressResponse) GetProgress() *TaskProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type GetTaskStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *TaskStatistics        `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"` // 任务统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskStatisticsResponse) Reset() {
	*x = GetTaskStatisticsResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStatisticsResponse) ProtoMessage() {}

func (x *GetTaskStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskStatisticsResponse) GetStatistics() *TaskStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// --- 系统统计 ---
type GetSystemStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatisticsRequest) Reset() {
	*x = GetSystemStatisticsRequest{}
	mi := &file_stress_v1_stress_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatisticsRequest) ProtoMessage() {}

func (x *GetSystemStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{13}
}

type GetSystemStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *SystemStatistics      `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"` // 系统统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatisticsResponse) Reset() {
	*x = GetSystemStatisticsResponse{}
	mi := &file_stress_v1_stress_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatisticsResponse) ProtoMessage() {}

func (x *GetSystemStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{14}
}

func (x *GetSystemStatisticsResponse) GetStatistics() *SystemStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// 游戏信息
type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`       // 游戏ID
	GameName      string                 `protobuf:"bytes,2,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`  // 游戏名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`            // 游戏描述
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"` // 是否激活
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_stress_v1_stress_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{15}
}

func (x *Game) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Game) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *Game) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Game) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// 任务配置
type TaskConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GameId         int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                           // 游戏ID
	MemberCount    int32                  `protobuf:"varint,2,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`            // 用户数量
	TimesPerMember int32                  `protobuf:"varint,3,opt,name=times_per_member,json=timesPerMember,proto3" json:"times_per_member,omitempty"` // 每个用户执行次数
	BetOrder       *BetOrderConfig        `protobuf:"bytes,4,opt,name=bet_order,json=betOrder,proto3" json:"bet_order,omitempty"`                      // 下注配置
	BetBonus       []*BetBonusConfig      `protobuf:"bytes,5,rep,name=bet_bonus,json=betBonus,proto3" json:"bet_bonus,omitempty"`                      // 奖励配置
	ApiUrl         string                 `protobuf:"bytes,6,opt,name=api_url,json=apiUrl,proto3" json:"api_url,omitempty"`                            // API地址
	LaunchUrl      string                 `protobuf:"bytes,7,opt,name=launch_url,json=launchUrl,proto3" json:"launch_url,omitempty"`                   // 启动地址
	SignRequired   bool                   `protobuf:"varint,8,opt,name=sign_required,json=signRequired,proto3" json:"sign_required,omitempty"`         // 是否需要签名
	Merchant       string                 `protobuf:"bytes,9,opt,name=merchant,proto3" json:"merchant,omitempty"`                                      // 商户名称
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskConfig) Reset() {
	*x = TaskConfig{}
	mi := &file_stress_v1_stress_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskConfig) ProtoMessage() {}

func (x *TaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskConfig.ProtoReflect.Descriptor instead.
func (*TaskConfig) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{16}
}

func (x *TaskConfig) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *TaskConfig) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *TaskConfig) GetTimesPerMember() int32 {
	if x != nil {
		return x.TimesPerMember
	}
	return 0
}

func (x *TaskConfig) GetBetOrder() *BetOrderConfig {
	if x != nil {
		return x.BetOrder
	}
	return nil
}

func (x *TaskConfig) GetBetBonus() []*BetBonusConfig {
	if x != nil {
		return x.BetBonus
	}
	return nil
}

func (x *TaskConfig) GetApiUrl() string {
	if x != nil {
		return x.ApiUrl
	}
	return ""
}

func (x *TaskConfig) GetLaunchUrl() string {
	if x != nil {
		return x.LaunchUrl
	}
	return ""
}

func (x *TaskConfig) GetSignRequired() bool {
	if x != nil {
		return x.SignRequired
	}
	return false
}

func (x *TaskConfig) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

// 下注配置
type BetOrderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseMoney     float64                `protobuf:"fixed64,1,opt,name=base_money,json=baseMoney,proto3" json:"base_money,omitempty"` // 基础金额
	Multiple      int64                  `protobuf:"varint,2,opt,name=multiple,proto3" json:"multiple,omitempty"`                     // 倍数
	Purchase      int64                  `protobuf:"varint,3,opt,name=purchase,proto3" json:"purchase,omitempty"`                     // 购买次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetOrderConfig) Reset() {
	*x = BetOrderConfig{}
	mi := &file_stress_v1_stress_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetOrderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetOrderConfig) ProtoMessage() {}

func (x *BetOrderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetOrderConfig.ProtoReflect.Descriptor instead.
func (*BetOrderConfig) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{17}
}

func (x *BetOrderConfig) GetBaseMoney() float64 {
	if x != nil {
		return x.BaseMoney
	}
	return 0
}

func (x *BetOrderConfig) GetMultiple() int64 {
	if x != nil {
		return x.Multiple
	}
	return 0
}

func (x *BetOrderConfig) GetPurchase() int64 {
	if x != nil {
		return x.Purchase
	}
	return 0
}

// 奖励配置
type BetBonusConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int64                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                             // 游戏ID
	BonusNum      int64                  `protobuf:"varint,2,opt,name=bonus_num,json=bonusNum,proto3" json:"bonus_num,omitempty"`                       // 指定奖励编号（0表示随机）
	RandomNums    []int64                `protobuf:"varint,3,rep,packed,name=random_nums,json=randomNums,proto3" json:"random_nums,omitempty"`          // 随机范围 [min, max]
	BonusSequence []int64                `protobuf:"varint,4,rep,packed,name=bonus_sequence,json=bonusSequence,proto3" json:"bonus_sequence,omitempty"` // 奖励序列
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BetBonusConfig) Reset() {
	*x = BetBonusConfig{}
	mi := &file_stress_v1_stress_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BetBonusConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetBonusConfig) ProtoMessage() {}

func (x *BetBonusConfig) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetBonusConfig.ProtoReflect.Descriptor instead.
func (*BetBonusConfig) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{18}
}

func (x *BetBonusConfig) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *BetBonusConfig) GetBonusNum() int64 {
	if x != nil {
		return x.BonusNum
	}
	return 0
}

func (x *BetBonusConfig) GetRandomNums() []int64 {
	if x != nil {
		return x.RandomNums
	}
	return nil
}

func (x *BetBonusConfig) GetBonusSequence() []int64 {
	if x != nil {
		return x.BonusSequence
	}
	return nil
}

// 任务完整信息
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`              // 任务ID
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                  // 任务描述
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=stress.v1.TaskStatus" json:"status,omitempty"` // 任务状态
	Config        *TaskConfig            `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`                            // 任务配置
	Progress      *TaskProgress          `protobuf:"bytes,5,opt,name=progress,proto3" json:"progress,omitempty"`                        // 任务进度
	Statistics    *TaskStatistics        `protobuf:"bytes,6,opt,name=statistics,proto3" json:"statistics,omitempty"`                    // 任务统计
	UserCount     int32                  `protobuf:"varint,7,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`    // 分配到的用户数量
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`     // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`     // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_stress_v1_stress_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{19}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_UNSPECIFIED
}

func (x *Task) GetConfig() *TaskConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Task) GetProgress() *TaskProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *Task) GetStatistics() *TaskStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *Task) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 任务进度
type TaskProgress struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalMembers      int32                  `protobuf:"varint,1,opt,name=total_members,json=totalMembers,proto3" json:"total_members,omitempty"`                // 总用户数
	CompletedMembers  int32                  `protobuf:"varint,2,opt,name=completed_members,json=completedMembers,proto3" json:"completed_members,omitempty"`    // 已完成用户数
	ActiveMembers     int32                  `protobuf:"varint,3,opt,name=active_members,json=activeMembers,proto3" json:"active_members,omitempty"`             // 活跃用户数
	FailedMembers     int32                  `protobuf:"varint,4,opt,name=failed_members,json=failedMembers,proto3" json:"failed_members,omitempty"`             // 失败用户数
	TotalRequests     int64                  `protobuf:"varint,5,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`             // 总请求数
	CompletedRequests int64                  `protobuf:"varint,6,opt,name=completed_requests,json=completedRequests,proto3" json:"completed_requests,omitempty"` // 已完成请求数
	FailedRequests    int64                  `protobuf:"varint,7,opt,name=failed_requests,json=failedRequests,proto3" json:"failed_requests,omitempty"`          // 失败请求数
	CompletionRate    float64                `protobuf:"fixed64,8,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`         // 完成率（0-1）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_stress_v1_stress_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{20}
}

func (x *TaskProgress) GetTotalMembers() int32 {
	if x != nil {
		return x.TotalMembers
	}
	return 0
}

func (x *TaskProgress) GetCompletedMembers() int32 {
	if x != nil {
		return x.CompletedMembers
	}
	return 0
}

func (x *TaskProgress) GetActiveMembers() int32 {
	if x != nil {
		return x.ActiveMembers
	}
	return 0
}

func (x *TaskProgress) GetFailedMembers() int32 {
	if x != nil {
		return x.FailedMembers
	}
	return 0
}

func (x *TaskProgress) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *TaskProgress) GetCompletedRequests() int64 {
	if x != nil {
		return x.CompletedRequests
	}
	return 0
}

func (x *TaskProgress) GetFailedRequests() int64 {
	if x != nil {
		return x.FailedRequests
	}
	return 0
}

func (x *TaskProgress) GetCompletionRate() float64 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

// 任务统计
type TaskStatistics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartTime         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                                                                                  // 开始时间
	EndTime           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                                                                                        // 结束时间
	TotalDurationMs   int64                  `protobuf:"varint,3,opt,name=total_duration_ms,json=totalDurationMs,proto3" json:"total_duration_ms,omitempty"`                                                             // 总耗时（毫秒）
	AvgResponseTimeMs float64                `protobuf:"fixed64,4,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`                                                    // 平均响应时间（毫秒）
	Qps               float64                `protobuf:"fixed64,5,opt,name=qps,proto3" json:"qps,omitempty"`                                                                                                             // QPS
	SuccessRate       float64                `protobuf:"fixed64,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`                                                                          // 成功率
	TotalBetOrders    int64                  `protobuf:"varint,7,opt,name=total_bet_orders,json=totalBetOrders,proto3" json:"total_bet_orders,omitempty"`                                                                // 总下注次数
	TotalBetBonuses   int64                  `protobuf:"varint,8,opt,name=total_bet_bonuses,json=totalBetBonuses,proto3" json:"total_bet_bonuses,omitempty"`                                                             // 总奖励次数
	ErrorCounts       map[string]int64       `protobuf:"bytes,9,rep,name=error_counts,json=errorCounts,proto3" json:"error_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 错误统计
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskStatistics) Reset() {
	*x = TaskStatistics{}
	mi := &file_stress_v1_stress_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatistics) ProtoMessage() {}

func (x *TaskStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatistics.ProtoReflect.Descriptor instead.
func (*TaskStatistics) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{21}
}

func (x *TaskStatistics) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TaskStatistics) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TaskStatistics) GetTotalDurationMs() int64 {
	if x != nil {
		return x.TotalDurationMs
	}
	return 0
}

func (x *TaskStatistics) GetAvgResponseTimeMs() float64 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

func (x *TaskStatistics) GetQps() float64 {
	if x != nil {
		return x.Qps
	}
	return 0
}

func (x *TaskStatistics) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *TaskStatistics) GetTotalBetOrders() int64 {
	if x != nil {
		return x.TotalBetOrders
	}
	return 0
}

func (x *TaskStatistics) GetTotalBetBonuses() int64 {
	if x != nil {
		return x.TotalBetBonuses
	}
	return 0
}

func (x *TaskStatistics) GetErrorCounts() map[string]int64 {
	if x != nil {
		return x.ErrorCounts
	}
	return nil
}

// 系统统计
type SystemStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalGames    int32                  `protobuf:"varint,1,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`       // 总游戏数
	ActiveGames   int32                  `protobuf:"varint,2,opt,name=active_games,json=activeGames,proto3" json:"active_games,omitempty"`    // 活跃游戏数
	TotalUsers    int32                  `protobuf:"varint,3,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`       // 总用户数
	ActiveUsers   int32                  `protobuf:"varint,4,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`    // 活跃用户数
	RunningTasks  int32                  `protobuf:"varint,5,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"` // 运行中任务数
	PendingTasks  int32                  `protobuf:"varint,6,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"` // 等待中任务数
	CollectedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`     // 收集时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatistics) Reset() {
	*x = SystemStatistics{}
	mi := &file_stress_v1_stress_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatistics) ProtoMessage() {}

func (x *SystemStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_stress_v1_stress_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatistics.ProtoReflect.Descriptor instead.
func (*SystemStatistics) Descriptor() ([]byte, []int) {
	return file_stress_v1_stress_proto_rawDescGZIP(), []int{22}
}

func (x *SystemStatistics) GetTotalGames() int32 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *SystemStatistics) GetActiveGames() int32 {
	if x != nil {
		return x.ActiveGames
	}
	return 0
}

func (x *SystemStatistics) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *SystemStatistics) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *SystemStatistics) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *SystemStatistics) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *SystemStatistics) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

var File_stress_v1_stress_proto protoreflect.FileDescriptor

const file_stress_v1_stress_proto_rawDesc = "" +
	"\n" +
	"\x16stress/v1/stress.proto\x12\tstress.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"%\n" +
	"\tPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10ListGamesRequest\"P\n" +
	"\x11ListGamesResponse\x12%\n" +
	"\x05games\x18\x01 \x03(\v2\x0f.stress.v1.GameR\x05games\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"n\n" +
	"\x11CreateTaskRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x127\n" +
	"\x06config\x18\x02 \x01(\v2\x15.stress.v1.TaskConfigB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06config\"9\n" +
	"\x12CreateTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.stress.v1.TaskR\x04task\"/\n" +
	"\vTaskRequest\x12 \n" +
	"\atask_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06taskId\"6\n" +
	"\x0fGetTaskResponse\x12#\n" +
	"\x04task\x18\x01 \x01(\v2\x0f.stress.v1.TaskR\x04task\"Y\n" +
	"\x10ListTasksRequest\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.stress.v1.TaskStatusR\x06status\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\"P\n" +
	"\x11ListTasksResponse\x12%\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0f.stress.v1.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"I\n" +
	"\x16GetTaskUserIdsResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"N\n" +
	"\x17GetTaskProgressResponse\x123\n" +
	"\bprogress\x18\x01 \x01(\v2\x17.stress.v1.TaskProgressR\bprogress\"V\n" +
	"\x19GetTaskStatisticsResponse\x129\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x19.stress.v1.TaskStatisticsR\n" +
	"statistics\"\x1c\n" +
	"\x1aGetSystemStatisticsRequest\"Z\n" +
	"\x1bGetSystemStatisticsResponse\x12;\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x1b.stress.v1.SystemStatisticsR\n" +
	"statistics\"{\n" +
	"\x04Game\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x03R\x06gameId\x12\x1b\n" +
	"\tgame_name\x18\x02 \x01(\tR\bgameName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"\x8e\x03\n" +
	"\n" +
	"TaskConfig\x12 \n" +
	"\agame_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06gameId\x12-\n" +
	"\fmember_count\x18\x02 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90N(\x01R\vmemberCount\x124\n" +
	"\x10times_per_member\x18\x03 \x01(\x05B\n" +
	"\xfaB\a\x1a\x05\x18\x90N(\x01R\x0etimesPerMember\x126\n" +
	"\tbet_order\x18\x04 \x01(\v2\x19.stress.v1.BetOrderConfigR\bbetOrder\x126\n" +
	"\tbet_bonus\x18\x05 \x03(\v2\x19.stress.v1.BetBonusConfigR\bbetBonus\x12 \n" +
	"\aapi_url\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06apiUrl\x12&\n" +
	"\n" +
	"launch_url\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tlaunchUrl\x12#\n" +
	"\rsign_required\x18\b \x01(\bR\fsignRequired\x12\x1a\n" +
	"\bmerchant\x18\t \x01(\tR\bmerchant\"\x89\x01\n" +
	"\x0eBetOrderConfig\x12-\n" +
	"\n" +
	"base_money\x18\x01 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\tbaseMoney\x12#\n" +
	"\bmultiple\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bmultiple\x12#\n" +
	"\bpurchase\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\bpurchase\"\x97\x01\n" +
	"\x0eBetBonusConfig\x12 \n" +
	"\agame_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06gameId\x12\x1b\n" +
	"\tbonus_num\x18\x02 \x01(\x03R\bbonusNum\x12\x1f\n" +
	"\vrandom_nums\x18\x03 \x03(\x03R\n" +
	"randomNums\x12%\n" +
	"\x0ebonus_sequence\x18\x04 \x03(\x03R\rbonusSequence\"\xa4\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.stress.v1.TaskStatusR\x06status\x12-\n" +
	"\x06config\x18\x04 \x01(\v2\x15.stress.v1.TaskConfigR\x06config\x123\n" +
	"\bprogress\x18\x05 \x01(\v2\x17.stress.v1.TaskProgressR\bprogress\x129\n" +
	"\n" +
	"statistics\x18\x06 \x01(\v2\x19.stress.v1.TaskStatisticsR\n" +
	"statistics\x12\x1d\n" +
	"\n" +
	"user_count\x18\a \x01(\x05R\tuserCount\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd6\x02\n" +
	"\fTaskProgress\x12#\n" +
	"\rtotal_members\x18\x01 \x01(\x05R\ftotalMembers\x12+\n" +
	"\x11completed_members\x18\x02 \x01(\x05R\x10completedMembers\x12%\n" +
	"\x0eactive_members\x18\x03 \x01(\x05R\ractiveMembers\x12%\n" +
	"\x0efailed_members\x18\x04 \x01(\x05R\rfailedMembers\x12%\n" +
	"\x0etotal_requests\x18\x05 \x01(\x03R\rtotalRequests\x12-\n" +
	"\x12completed_requests\x18\x06 \x01(\x03R\x11completedRequests\x12'\n" +
	"\x0ffailed_requests\x18\a \x01(\x03R\x0efailedRequests\x12'\n" +
	"\x0fcompletion_rate\x18\b \x01(\x01R\x0ecompletionRate\"\xf9\x03\n" +
	"\x0eTaskStatistics\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12*\n" +
	"\x11total_duration_ms\x18\x03 \x01(\x03R\x0ftotalDurationMs\x12/\n" +
	"\x14avg_response_time_ms\x18\x04 \x01(\x01R\x11avgResponseTimeMs\x12\x10\n" +
	"\x03qps\x18\x05 \x01(\x01R\x03qps\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x01R\vsuccessRate\x12(\n" +
	"\x10total_bet_orders\x18\a \x01(\x03R\x0etotalBetOrders\x12*\n" +
	"\x11total_bet_bonuses\x18\b \x01(\x03R\x0ftotalBetBonuses\x12M\n" +
	"\ferror_counts\x18\t \x03(\v2*.stress.v1.TaskStatistics.ErrorCountsEntryR\verrorCounts\x1a>\n" +
	"\x10ErrorCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xa3\x02\n" +
	"\x10SystemStatistics\x12\x1f\n" +
	"\vtotal_games\x18\x01 \x01(\x05R\n" +
	"totalGames\x12!\n" +
	"\factive_games\x18\x02 \x01(\x05R\vactiveGames\x12\x1f\n" +
	"\vtotal_users\x18\x03 \x01(\x05R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x04 \x01(\x05R\vactiveUsers\x12#\n" +
	"\rrunning_tasks\x18\x05 \x01(\x05R\frunningTasks\x12#\n" +
	"\rpending_tasks\x18\x06 \x01(\x05R\fpendingTasks\x12=\n" +
	"\fcollected_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt*\x7f\n" +
	"\n" +
	"TaskStatus\x12\x14\n" +
	"\x10TASK_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTASK_PENDING\x10\x01\x12\x10\n" +
	"\fTASK_RUNNING\x10\x02\x12\x12\n" +
	"\x0eTASK_COMPLETED\x10\x03\x12\x0f\n" +
	"\vTASK_FAILED\x10\x04\x12\x12\n" +
	"\x0eTASK_CANCELLED\x10\x052\xbf\t\n" +
	"\rStressService\x12T\n" +
	"\aPingReq\x12\x16.stress.v1.PingRequest\x1a\x14.stress.v1.PingReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/stress/ping/{name}\x12a\n" +
	"\tListGames\x12\x1b.stress.v1.ListGamesRequest\x1a\x1c.stress.v1.ListGamesResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/stress/ListGames\x12a\n" +
	"\tListTasks\x12\x1b.stress.v1.ListTasksRequest\x1a\x1c.stress.v1.ListTasksResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/stress/ListTasks\x12h\n" +
	"\n" +
	"CreateTask\x12\x1c.stress.v1.CreateTaskRequest\x1a\x1d.stress.v1.CreateTaskResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/stress/CreateTask\x12`\n" +
	"\aGetTask\x12\x16.stress.v1.TaskRequest\x1a\x1a.stress.v1.GetTaskResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/stress/GetTask/{task_id}\x12~\n" +
	"\x0eGetTaskUserIds\x12\x16.stress.v1.TaskRequest\x1a!.stress.v1.GetTaskUserIdsResponse\"1\x82\xd3\xe4\x93\x02+\x12)/stress/GetTaskUserIds/{task_id}/user_ids\x12b\n" +
	"\n" +
	"DeleteTask\x12\x16.stress.v1.TaskRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/stress/DeleteTask/{task_id}\x12e\n" +
	"\n" +
	"CancelTask\x12\x16.stress.v1.TaskRequest\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/stress/CancelTask/{task_id}\x12x\n" +
	"\x0fGetTaskProgress\x12\x16.stress.v1.TaskRequest\x1a\".stress.v1.GetTaskProgressResponse\")\x82\xd3\xe4\x93\x02#\x12!/stress/GetTaskProgress/{task_id}\x12~\n" +
	"\x11GetTaskStatistics\x12\x16.stress.v1.TaskRequest\x1a$.stress.v1.GetTaskStatisticsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/stress/GetTaskStatistics/{task_id}\x12\x80\x01\n" +
	"\x13GetSystemStatistics\x12%.stress.v1.GetSystemStatisticsRequest\x1a&.stress.v1.GetSystemStatisticsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/stress/statisticsBD\n" +
	"\x18dev.kratos.api.stress.v1B\rStressProtoV1P\x01Z\x17stress/api/stress/v1;v1b\x06proto3"

var (
	file_stress_v1_stress_proto_rawDescOnce sync.Once
	file_stress_v1_stress_proto_rawDescData []byte
)

func file_stress_v1_stress_proto_rawDescGZIP() []byte {
	file_stress_v1_stress_proto_rawDescOnce.Do(func() {
		file_stress_v1_stress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stress_v1_stress_proto_rawDesc), len(file_stress_v1_stress_proto_rawDesc)))
	})
	return file_stress_v1_stress_proto_rawDescData
}

var file_stress_v1_stress_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_stress_v1_stress_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_stress_v1_stress_proto_goTypes = []any{
	(TaskStatus)(0),                     // 0: stress.v1.TaskStatus
	(*PingRequest)(nil),                 // 1: stress.v1.PingRequest
	(*PingReply)(nil),                   // 2: stress.v1.PingReply
	(*ListGamesRequest)(nil),            // 3: stress.v1.ListGamesRequest
	(*ListGamesResponse)(nil),           // 4: stress.v1.ListGamesResponse
	(*CreateTaskRequest)(nil),           // 5: stress.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),          // 6: stress.v1.CreateTaskResponse
	(*TaskRequest)(nil),                 // 7: stress.v1.TaskRequest
	(*GetTaskResponse)(nil),             // 8: stress.v1.GetTaskResponse
	(*ListTasksRequest)(nil),            // 9: stress.v1.ListTasksRequest
	(*ListTasksResponse)(nil),           // 10: stress.v1.ListTasksResponse
	(*GetTaskUserIdsResponse)(nil),      // 11: stress.v1.GetTaskUserIdsResponse
	(*GetTaskProgressResponse)(nil),     // 12: stress.v1.GetTaskProgressResponse
	(*GetTaskStatisticsResponse)(nil),   // 13: stress.v1.GetTaskStatisticsResponse
	(*GetSystemStatisticsRequest)(nil),  // 14: stress.v1.GetSystemStatisticsRequest
	(*GetSystemStatisticsResponse)(nil), // 15: stress.v1.GetSystemStatisticsResponse
	(*Game)(nil),                        // 16: stress.v1.Game
	(*TaskConfig)(nil),                  // 17: stress.v1.TaskConfig
	(*BetOrderConfig)(nil),              // 18: stress.v1.BetOrderConfig
	(*BetBonusConfig)(nil),              // 19: stress.v1.BetBonusConfig
	(*Task)(nil),                        // 20: stress.v1.Task
	(*TaskProgress)(nil),                // 21: stress.v1.TaskProgress
	(*TaskStatistics)(nil),              // 22: stress.v1.TaskStatistics
	(*SystemStatistics)(nil),            // 23: stress.v1.SystemStatistics
	nil,                                 // 24: stress.v1.TaskStatistics.ErrorCountsEntry
	(*timestamppb.Timestamp)(nil),       // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 26: google.protobuf.Empty
}
var file_stress_v1_stress_proto_depIdxs = []int32{
	16, // 0: stress.v1.ListGamesResponse.games:type_name -> stress.v1.Game
	17, // 1: stress.v1.CreateTaskRequest.config:type_name -> stress.v1.TaskConfig
	20, // 2: stress.v1.CreateTaskResponse.task:type_name -> stress.v1.Task
	20, // 3: stress.v1.GetTaskResponse.task:type_name -> stress.v1.Task
	0,  // 4: stress.v1.ListTasksRequest.status:type_name -> stress.v1.TaskStatus
	20, // 5: stress.v1.ListTasksResponse.tasks:type_name -> stress.v1.Task
	21, // 6: stress.v1.GetTaskProgressResponse.progress:type_name -> stress.v1.TaskProgress
	22, // 7: stress.v1.GetTaskStatisticsResponse.statistics:type_name -> stress.v1.TaskStatistics
	23, // 8: stress.v1.GetSystemStatisticsResponse.statistics:type_name -> stress.v1.SystemStatistics
	18, // 9: stress.v1.TaskConfig.bet_order:type_name -> stress.v1.BetOrderConfig
	19, // 10: stress.v1.TaskConfig.bet_bonus:type_name -> stress.v1.BetBonusConfig
	0,  // 11: stress.v1.Task.status:type_name -> stress.v1.TaskStatus
	17, // 12: stress.v1.Task.config:type_name -> stress.v1.TaskConfig
	21, // 13: stress.v1.Task.progress:type_name -> stress.v1.TaskProgress
	22, // 14: stress.v1.Task.statistics:type_name -> stress.v1.TaskStatistics
	25, // 15: stress.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	25, // 16: stress.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	25, // 17: stress.v1.TaskStatistics.start_time:type_name -> google.protobuf.Timestamp
	25, // 18: stress.v1.TaskStatistics.end_time:type_name -> google.protobuf.Timestamp
	24, // 19: stress.v1.TaskStatistics.error_counts:type_name -> stress.v1.TaskStatistics.ErrorCountsEntry
	25, // 20: stress.v1.SystemStatistics.collected_at:type_name -> google.protobuf.Timestamp
	1,  // 21: stress.v1.StressService.PingReq:input_type -> stress.v1.PingRequest
	3,  // 22: stress.v1.StressService.ListGames:input_type -> stress.v1.ListGamesRequest
	9,  // 23: stress.v1.StressService.ListTasks:input_type -> stress.v1.ListTasksRequest
	5,  // 24: stress.v1.StressService.CreateTask:input_type -> stress.v1.CreateTaskRequest
	7,  // 25: stress.v1.StressService.GetTask:input_type -> stress.v1.TaskRequest
	7,  // 26: stress.v1.StressService.GetTaskUserIds:input_type -> stress.v1.TaskRequest
	7,  // 27: stress.v1.StressService.DeleteTask:input_type -> stress.v1.TaskRequest
	7,  // 28: stress.v1.StressService.CancelTask:input_type -> stress.v1.TaskRequest
	7,  // 29: stress.v1.StressService.GetTaskProgress:input_type -> stress.v1.TaskRequest
	7,  // 30: stress.v1.StressService.GetTaskStatistics:input_type -> stress.v1.TaskRequest
	14, // 31: stress.v1.StressService.GetSystemStatistics:input_type -> stress.v1.GetSystemStatisticsRequest
	2,  // 32: stress.v1.StressService.PingReq:output_type -> stress.v1.PingReply
	4,  // 33: stress.v1.StressService.ListGames:output_type -> stress.v1.ListGamesResponse
	10, // 34: stress.v1.StressService.ListTasks:output_type -> stress.v1.ListTasksResponse
	6,  // 35: stress.v1.StressService.CreateTask:output_type -> stress.v1.CreateTaskResponse
	8,  // 36: stress.v1.StressService.GetTask:output_type -> stress.v1.GetTaskResponse
	11, // 37: stress.v1.StressService.GetTaskUserIds:output_type -> stress.v1.GetTaskUserIdsResponse
	26, // 38: stress.v1.StressService.DeleteTask:output_type -> google.protobuf.Empty
	26, // 39: stress.v1.StressService.CancelTask:output_type -> google.protobuf.Empty
	12, // 40: stress.v1.StressService.GetTaskProgress:output_type -> stress.v1.GetTaskProgressResponse
	13, // 41: stress.v1.StressService.GetTaskStatistics:output_type -> stress.v1.GetTaskStatisticsResponse
	15, // 42: stress.v1.StressService.GetSystemStatistics:output_type -> stress.v1.GetSystemStatisticsResponse
	32, // [32:43] is the sub-list for method output_type
	21, // [21:32] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_stress_v1_stress_proto_init() }
func file_stress_v1_stress_proto_init() {
	if File_stress_v1_stress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stress_v1_stress_proto_rawDesc), len(file_stress_v1_stress_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stress_v1_stress_proto_goTypes,
		DependencyIndexes: file_stress_v1_stress_proto_depIdxs,
		EnumInfos:         file_stress_v1_stress_proto_enumTypes,
		MessageInfos:      file_stress_v1_stress_proto_msgTypes,
	}.Build()
	File_stress_v1_stress_proto = out.File
	file_stress_v1_stress_proto_goTypes = nil
	file_stress_v1_stress_proto_depIdxs = nil
}
