// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: dhhj.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 中奖详情响应
type Dhhj_BetOrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单 / 账户
	Sn      *string  `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn"`             // 订单号
	Balance *float64 `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance"` // 当前余额
	// 下注信息
	BaseBet    *float64 `protobuf:"fixed64,3,opt,name=baseBet,proto3,oneof" json:"baseBet"`      // 基础下注
	BetAmount  *float64 `protobuf:"fixed64,4,opt,name=betAmount,proto3,oneof" json:"betAmount"`  // 实际投注金额（baseBet × multiplier）
	Multiplier *int64   `protobuf:"varint,5,opt,name=multiplier,proto3,oneof" json:"multiplier"` // 下注倍数
	Board      *Board   `protobuf:"bytes,6,opt,name=board,proto3,oneof" json:"board"`            // 当前 step 结算盘面（用于展示本次响应结果）
	// 赢分层级
	CurWin       *float64 `protobuf:"fixed64,7,opt,name=curWin,proto3,oneof" json:"curWin"`              // step：本次 betOrder 赢分
	RoundWin     *float64 `protobuf:"fixed64,8,opt,name=roundWin,proto3,oneof" json:"roundWin"`          // round：本回合累计赢（消除类多步累计）
	TotalWin     *float64 `protobuf:"fixed64,9,opt,name=totalWin,proto3,oneof" json:"totalWin"`          // spin：本 spin 总赢（含免费触发轮）
	FreeTotalWin *float64 `protobuf:"fixed64,10,opt,name=freeTotalWin,proto3,oneof" json:"freeTotalWin"` // 免费局阶段累计总赢（不含触发轮）
	// 流程控制
	IsRoundOver *bool  `protobuf:"varint,11,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver"` // 本 round 是否结束
	IsSpinOver  *bool  `protobuf:"varint,12,opt,name=isSpinOver,proto3,oneof" json:"isSpinOver"`   // 本次是否需要继续调用 BetOrder：false-继续（cascade/respin）；true-结束或等待 BetBonus
	NextState   *int64 `protobuf:"varint,13,opt,name=nextState,proto3,oneof" json:"nextState"`     // 下一阶段提示：0-无；1-进入 bonus 选择（需 BetBonus）；2-BetBonus 确认后进入免费（bonusState=2）
	BonusState  *int64 `protobuf:"varint,14,opt,name=bonusState,proto3,oneof" json:"bonusState"`   // 当前 bonus 状态：0-普通；1-等待选择；2-免费回合中
	// 免费游戏
	IsFree                   *bool                `protobuf:"varint,15,opt,name=isFree,proto3,oneof" json:"isFree"`                                     // 当前 step 是否为免费结算（bonusState=2）
	NewFreeTimes             *uint64              `protobuf:"varint,16,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes"`                         // 本 step retrigger 新增免费次数（首次进入免费由 BetBonus 决定）
	RemainingFreeTimes       *uint64              `protobuf:"varint,17,opt,name=remainingFreeTimes,proto3,oneof" json:"remainingFreeTimes"`             // 剩余免费次数（freeNum）
	TotalFreeTimes           *uint64              `protobuf:"varint,18,opt,name=totalFreeTimes,proto3,oneof" json:"totalFreeTimes"`                     // 免费次数汇总（已消耗 freeTimes + 剩余 remainingFreeTimes）
	ScatterCount             *int64               `protobuf:"varint,19,opt,name=scatterCount,proto3,oneof" json:"scatterCount"`                         // 当前 step 盘面中的 scatter 数（用于触发选择/免费/retrigger 判定）
	WinArr                   []*WayWinResult      `protobuf:"bytes,20,rep,name=winArr,proto3" json:"winArr"`                                            // Way 中奖结果列表
	Review                   *int64               `protobuf:"varint,21,opt,name=review,proto3,oneof" json:"review"`                                     // 审核状态
	NextBoard                *Board               `protobuf:"bytes,22,opt,name=nextBoard,proto3,oneof" json:"nextBoard"`                                // 下一 step 续算盘面（仅 isSpinOver=false 且非 respin 起手时有效；否则为空）
	WinGrid                  *Board               `protobuf:"bytes,23,opt,name=winGrid,proto3,oneof" json:"winGrid"`                                    // 本 step 中奖覆盖网格（非 0 表示参与中奖的 symbolId）
	WildEffects              *Board               `protobuf:"bytes,25,opt,name=wildEffects,proto3,oneof" json:"wildEffects"`                            // wildEffects：效果层叠加（0-无；1/2-火枪剩余命数；9-红宝石转 scatter；11-瓷器感染）
	BonusOptions             []*Dhhj_BonusOptions `protobuf:"bytes,26,rep,name=bonusOptions,proto3" json:"bonusOptions"`                                // bonus 选项列表（仅 bonusState=1 返回）
	SelectedBonus            *int64               `protobuf:"varint,27,opt,name=selectedBonus,proto3,oneof" json:"selectedBonus"`                       // 已选择的 bonus ID（1..4，仅 bonusState=2 有意义）
	FreeMulLevel             *int64               `protobuf:"varint,28,opt,name=freeMulLevel,proto3,oneof" json:"freeMulLevel"`                         // free head multiplier 等级（仅 bonusState=2，随消除递增）
	FreeMulValue             *int64               `protobuf:"varint,29,opt,name=freeMulValue,proto3,oneof" json:"freeMulValue"`                         // free head multiplier 当前倍率（仅 bonusState=2）
	CascadeCount             *int64               `protobuf:"varint,30,opt,name=cascadeCount,proto3,oneof" json:"cascadeCount"`                         // 本 round 已发生的消除次数（有消除的 step 会递增）
	PorcelainSpread          []*PorcelainSpread   `protobuf:"bytes,31,rep,name=porcelainSpread,proto3" json:"porcelainSpread"`                          // 瓷器扩散事件（源->目标，索引规则同 Board.elements）
	Respin                   *bool                `protobuf:"varint,32,opt,name=respin,proto3,oneof" json:"respin"`                                     // 本 step 是否触发 respin
	RespinNewFreeTimes       *uint64              `protobuf:"varint,33,opt,name=respinNewFreeTimes,proto3,oneof" json:"respinNewFreeTimes"`             // 本 step retrigger 新增免费次
	RespinRemainingFreeTimes *uint64              `protobuf:"varint,34,opt,name=respinRemainingFreeTimes,proto3,oneof" json:"respinRemainingFreeTimes"` // 剩余免费次数
	RespinTotalFreeTimes     *uint64              `protobuf:"varint,35,opt,name=respinTotalFreeTimes,proto3,oneof" json:"respinTotalFreeTimes"`         // 免费次数汇总（已消耗 freeTimes + 剩余 remainingFreeTimes）
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Dhhj_BetOrderResponse) Reset() {
	*x = Dhhj_BetOrderResponse{}
	mi := &file_dhhj_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dhhj_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dhhj_BetOrderResponse) ProtoMessage() {}

func (x *Dhhj_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dhhj_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dhhj_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Dhhj_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_dhhj_proto_rawDescGZIP(), []int{0}
}

func (x *Dhhj_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Dhhj_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetBaseBet() float64 {
	if x != nil && x.BaseBet != nil {
		return *x.BaseBet
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Dhhj_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetRoundWin() float64 {
	if x != nil && x.RoundWin != nil {
		return *x.RoundWin
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetFreeTotalWin() float64 {
	if x != nil && x.FreeTotalWin != nil {
		return *x.FreeTotalWin
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Dhhj_BetOrderResponse) GetIsSpinOver() bool {
	if x != nil && x.IsSpinOver != nil {
		return *x.IsSpinOver
	}
	return false
}

func (x *Dhhj_BetOrderResponse) GetNextState() int64 {
	if x != nil && x.NextState != nil {
		return *x.NextState
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetBonusState() int64 {
	if x != nil && x.BonusState != nil {
		return *x.BonusState
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Dhhj_BetOrderResponse) GetNewFreeTimes() uint64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetRemainingFreeTimes() uint64 {
	if x != nil && x.RemainingFreeTimes != nil {
		return *x.RemainingFreeTimes
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetTotalFreeTimes() uint64 {
	if x != nil && x.TotalFreeTimes != nil {
		return *x.TotalFreeTimes
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetScatterCount() int64 {
	if x != nil && x.ScatterCount != nil {
		return *x.ScatterCount
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetWinArr() []*WayWinResult {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Dhhj_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetNextBoard() *Board {
	if x != nil {
		return x.NextBoard
	}
	return nil
}

func (x *Dhhj_BetOrderResponse) GetWinGrid() *Board {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Dhhj_BetOrderResponse) GetWildEffects() *Board {
	if x != nil {
		return x.WildEffects
	}
	return nil
}

func (x *Dhhj_BetOrderResponse) GetBonusOptions() []*Dhhj_BonusOptions {
	if x != nil {
		return x.BonusOptions
	}
	return nil
}

func (x *Dhhj_BetOrderResponse) GetSelectedBonus() int64 {
	if x != nil && x.SelectedBonus != nil {
		return *x.SelectedBonus
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetFreeMulLevel() int64 {
	if x != nil && x.FreeMulLevel != nil {
		return *x.FreeMulLevel
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetFreeMulValue() int64 {
	if x != nil && x.FreeMulValue != nil {
		return *x.FreeMulValue
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetCascadeCount() int64 {
	if x != nil && x.CascadeCount != nil {
		return *x.CascadeCount
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetPorcelainSpread() []*PorcelainSpread {
	if x != nil {
		return x.PorcelainSpread
	}
	return nil
}

func (x *Dhhj_BetOrderResponse) GetRespin() bool {
	if x != nil && x.Respin != nil {
		return *x.Respin
	}
	return false
}

func (x *Dhhj_BetOrderResponse) GetRespinNewFreeTimes() uint64 {
	if x != nil && x.RespinNewFreeTimes != nil {
		return *x.RespinNewFreeTimes
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetRespinRemainingFreeTimes() uint64 {
	if x != nil && x.RespinRemainingFreeTimes != nil {
		return *x.RespinRemainingFreeTimes
	}
	return 0
}

func (x *Dhhj_BetOrderResponse) GetRespinTotalFreeTimes() uint64 {
	if x != nil && x.RespinTotalFreeTimes != nil {
		return *x.RespinTotalFreeTimes
	}
	return 0
}

type Dhhj_BonusOptions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id"`                                     // 选项 ID（1..4）
	FreeSpins            *int64                 `protobuf:"varint,2,opt,name=freeSpins,proto3,oneof" json:"freeSpins"`                       // 基础 free 次数
	Multipliers          []int64                `protobuf:"varint,3,rep,packed,name=multipliers,proto3" json:"multipliers"`                  // free head multiplier 档位（随消除升级）
	ExtraSpinsPerScatter *int64                 `protobuf:"varint,4,opt,name=extraSpinsPerScatter,proto3,oneof" json:"extraSpinsPerScatter"` // 额外 scatter 每个增加的 free 次数
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Dhhj_BonusOptions) Reset() {
	*x = Dhhj_BonusOptions{}
	mi := &file_dhhj_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dhhj_BonusOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dhhj_BonusOptions) ProtoMessage() {}

func (x *Dhhj_BonusOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dhhj_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dhhj_BonusOptions.ProtoReflect.Descriptor instead.
func (*Dhhj_BonusOptions) Descriptor() ([]byte, []int) {
	return file_dhhj_proto_rawDescGZIP(), []int{1}
}

func (x *Dhhj_BonusOptions) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Dhhj_BonusOptions) GetFreeSpins() int64 {
	if x != nil && x.FreeSpins != nil {
		return *x.FreeSpins
	}
	return 0
}

func (x *Dhhj_BonusOptions) GetMultipliers() []int64 {
	if x != nil {
		return x.Multipliers
	}
	return nil
}

func (x *Dhhj_BonusOptions) GetExtraSpinsPerScatter() int64 {
	if x != nil && x.ExtraSpinsPerScatter != nil {
		return *x.ExtraSpinsPerScatter
	}
	return 0
}

type PorcelainSpread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIndex     *int64                 `protobuf:"varint,1,opt,name=fromIndex,proto3,oneof" json:"fromIndex"`
	ToIndex       *int64                 `protobuf:"varint,2,opt,name=toIndex,proto3,oneof" json:"toIndex"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PorcelainSpread) Reset() {
	*x = PorcelainSpread{}
	mi := &file_dhhj_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PorcelainSpread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PorcelainSpread) ProtoMessage() {}

func (x *PorcelainSpread) ProtoReflect() protoreflect.Message {
	mi := &file_dhhj_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PorcelainSpread.ProtoReflect.Descriptor instead.
func (*PorcelainSpread) Descriptor() ([]byte, []int) {
	return file_dhhj_proto_rawDescGZIP(), []int{2}
}

func (x *PorcelainSpread) GetFromIndex() int64 {
	if x != nil && x.FromIndex != nil {
		return *x.FromIndex
	}
	return 0
}

func (x *PorcelainSpread) GetToIndex() int64 {
	if x != nil && x.ToIndex != nil {
		return *x.ToIndex
	}
	return 0
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []int64                `protobuf:"varint,1,rep,packed,name=elements,proto3" json:"elements"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_dhhj_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_dhhj_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_dhhj_proto_rawDescGZIP(), []int{3}
}

func (x *Board) GetElements() []int64 {
	if x != nil {
		return x.Elements
	}
	return nil
}

// way 游戏
type WayWinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *int64                 `protobuf:"varint,1,opt,name=symbol,proto3,oneof" json:"symbol"`         // 符号
	SymbolNum     *int64                 `protobuf:"varint,2,opt,name=symbolNum,proto3,oneof" json:"symbolNum"`   // 数量
	RoadNum       *int64                 `protobuf:"varint,3,opt,name=roadNum,proto3,oneof" json:"roadNum"`       // 中间路数
	Multiplier    *int64                 `protobuf:"varint,4,opt,name=multiplier,proto3,oneof" json:"multiplier"` // 倍率
	Grid          *Board                 `protobuf:"bytes,5,opt,name=grid,proto3" json:"grid"`                    // 牌面
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WayWinResult) Reset() {
	*x = WayWinResult{}
	mi := &file_dhhj_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WayWinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WayWinResult) ProtoMessage() {}

func (x *WayWinResult) ProtoReflect() protoreflect.Message {
	mi := &file_dhhj_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WayWinResult.ProtoReflect.Descriptor instead.
func (*WayWinResult) Descriptor() ([]byte, []int) {
	return file_dhhj_proto_rawDescGZIP(), []int{4}
}

func (x *WayWinResult) GetSymbol() int64 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *WayWinResult) GetSymbolNum() int64 {
	if x != nil && x.SymbolNum != nil {
		return *x.SymbolNum
	}
	return 0
}

func (x *WayWinResult) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *WayWinResult) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *WayWinResult) GetGrid() *Board {
	if x != nil {
		return x.Grid
	}
	return nil
}

var File_dhhj_proto protoreflect.FileDescriptor

const file_dhhj_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"dhhj.proto\x12\x04dhhj\"\xf1\x0e\n" +
	"\x15dhhj_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12\x1d\n" +
	"\abaseBet\x18\x03 \x01(\x01H\x02R\abaseBet\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x04 \x01(\x01H\x03R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x05 \x01(\x03H\x04R\n" +
	"multiplier\x88\x01\x01\x12&\n" +
	"\x05board\x18\x06 \x01(\v2\v.dhhj.BoardH\x05R\x05board\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\a \x01(\x01H\x06R\x06curWin\x88\x01\x01\x12\x1f\n" +
	"\broundWin\x18\b \x01(\x01H\aR\broundWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\t \x01(\x01H\bR\btotalWin\x88\x01\x01\x12'\n" +
	"\ffreeTotalWin\x18\n" +
	" \x01(\x01H\tR\ffreeTotalWin\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\v \x01(\bH\n" +
	"R\visRoundOver\x88\x01\x01\x12#\n" +
	"\n" +
	"isSpinOver\x18\f \x01(\bH\vR\n" +
	"isSpinOver\x88\x01\x01\x12!\n" +
	"\tnextState\x18\r \x01(\x03H\fR\tnextState\x88\x01\x01\x12#\n" +
	"\n" +
	"bonusState\x18\x0e \x01(\x03H\rR\n" +
	"bonusState\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\x0f \x01(\bH\x0eR\x06isFree\x88\x01\x01\x12'\n" +
	"\fnewFreeTimes\x18\x10 \x01(\x04H\x0fR\fnewFreeTimes\x88\x01\x01\x123\n" +
	"\x12remainingFreeTimes\x18\x11 \x01(\x04H\x10R\x12remainingFreeTimes\x88\x01\x01\x12+\n" +
	"\x0etotalFreeTimes\x18\x12 \x01(\x04H\x11R\x0etotalFreeTimes\x88\x01\x01\x12'\n" +
	"\fscatterCount\x18\x13 \x01(\x03H\x12R\fscatterCount\x88\x01\x01\x12*\n" +
	"\x06winArr\x18\x14 \x03(\v2\x12.dhhj.WayWinResultR\x06winArr\x12\x1b\n" +
	"\x06review\x18\x15 \x01(\x03H\x13R\x06review\x88\x01\x01\x12.\n" +
	"\tnextBoard\x18\x16 \x01(\v2\v.dhhj.BoardH\x14R\tnextBoard\x88\x01\x01\x12*\n" +
	"\awinGrid\x18\x17 \x01(\v2\v.dhhj.BoardH\x15R\awinGrid\x88\x01\x01\x122\n" +
	"\vwildEffects\x18\x19 \x01(\v2\v.dhhj.BoardH\x16R\vwildEffects\x88\x01\x01\x12;\n" +
	"\fbonusOptions\x18\x1a \x03(\v2\x17.dhhj.dhhj_BonusOptionsR\fbonusOptions\x12)\n" +
	"\rselectedBonus\x18\x1b \x01(\x03H\x17R\rselectedBonus\x88\x01\x01\x12'\n" +
	"\ffreeMulLevel\x18\x1c \x01(\x03H\x18R\ffreeMulLevel\x88\x01\x01\x12'\n" +
	"\ffreeMulValue\x18\x1d \x01(\x03H\x19R\ffreeMulValue\x88\x01\x01\x12'\n" +
	"\fcascadeCount\x18\x1e \x01(\x03H\x1aR\fcascadeCount\x88\x01\x01\x12?\n" +
	"\x0fporcelainSpread\x18\x1f \x03(\v2\x15.dhhj.PorcelainSpreadR\x0fporcelainSpread\x12\x1b\n" +
	"\x06respin\x18  \x01(\bH\x1bR\x06respin\x88\x01\x01\x123\n" +
	"\x12respinNewFreeTimes\x18! \x01(\x04H\x1cR\x12respinNewFreeTimes\x88\x01\x01\x12?\n" +
	"\x18respinRemainingFreeTimes\x18\" \x01(\x04H\x1dR\x18respinRemainingFreeTimes\x88\x01\x01\x127\n" +
	"\x14respinTotalFreeTimes\x18# \x01(\x04H\x1eR\x14respinTotalFreeTimes\x88\x01\x01B\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\n" +
	"\n" +
	"\b_baseBetB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_multiplierB\b\n" +
	"\x06_boardB\t\n" +
	"\a_curWinB\v\n" +
	"\t_roundWinB\v\n" +
	"\t_totalWinB\x0f\n" +
	"\r_freeTotalWinB\x0e\n" +
	"\f_isRoundOverB\r\n" +
	"\v_isSpinOverB\f\n" +
	"\n" +
	"_nextStateB\r\n" +
	"\v_bonusStateB\t\n" +
	"\a_isFreeB\x0f\n" +
	"\r_newFreeTimesB\x15\n" +
	"\x13_remainingFreeTimesB\x11\n" +
	"\x0f_totalFreeTimesB\x0f\n" +
	"\r_scatterCountB\t\n" +
	"\a_reviewB\f\n" +
	"\n" +
	"_nextBoardB\n" +
	"\n" +
	"\b_winGridB\x0e\n" +
	"\f_wildEffectsB\x10\n" +
	"\x0e_selectedBonusB\x0f\n" +
	"\r_freeMulLevelB\x0f\n" +
	"\r_freeMulValueB\x0f\n" +
	"\r_cascadeCountB\t\n" +
	"\a_respinB\x15\n" +
	"\x13_respinNewFreeTimesB\x1b\n" +
	"\x19_respinRemainingFreeTimesB\x17\n" +
	"\x15_respinTotalFreeTimes\"\xd4\x01\n" +
	"\x11dhhj_BonusOptions\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12!\n" +
	"\tfreeSpins\x18\x02 \x01(\x03H\x01R\tfreeSpins\x88\x01\x01\x12 \n" +
	"\vmultipliers\x18\x03 \x03(\x03R\vmultipliers\x127\n" +
	"\x14extraSpinsPerScatter\x18\x04 \x01(\x03H\x02R\x14extraSpinsPerScatter\x88\x01\x01B\x05\n" +
	"\x03_idB\f\n" +
	"\n" +
	"_freeSpinsB\x17\n" +
	"\x15_extraSpinsPerScatter\"m\n" +
	"\x0fPorcelainSpread\x12!\n" +
	"\tfromIndex\x18\x01 \x01(\x03H\x00R\tfromIndex\x88\x01\x01\x12\x1d\n" +
	"\atoIndex\x18\x02 \x01(\x03H\x01R\atoIndex\x88\x01\x01B\f\n" +
	"\n" +
	"_fromIndexB\n" +
	"\n" +
	"\b_toIndex\"#\n" +
	"\x05Board\x12\x1a\n" +
	"\belements\x18\x01 \x03(\x03R\belements\"\xe7\x01\n" +
	"\fWayWinResult\x12\x1b\n" +
	"\x06symbol\x18\x01 \x01(\x03H\x00R\x06symbol\x88\x01\x01\x12!\n" +
	"\tsymbolNum\x18\x02 \x01(\x03H\x01R\tsymbolNum\x88\x01\x01\x12\x1d\n" +
	"\aroadNum\x18\x03 \x01(\x03H\x02R\aroadNum\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x03H\x03R\n" +
	"multiplier\x88\x01\x01\x12\x1f\n" +
	"\x04grid\x18\x05 \x01(\v2\v.dhhj.BoardR\x04gridB\t\n" +
	"\a_symbolB\f\n" +
	"\n" +
	"_symbolNumB\n" +
	"\n" +
	"\b_roadNumB\r\n" +
	"\v_multiplierB\x19Z\x17egame-grpc/game/dhhj/pbb\x06proto3"

var (
	file_dhhj_proto_rawDescOnce sync.Once
	file_dhhj_proto_rawDescData []byte
)

func file_dhhj_proto_rawDescGZIP() []byte {
	file_dhhj_proto_rawDescOnce.Do(func() {
		file_dhhj_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dhhj_proto_rawDesc), len(file_dhhj_proto_rawDesc)))
	})
	return file_dhhj_proto_rawDescData
}

var file_dhhj_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dhhj_proto_goTypes = []any{
	(*Dhhj_BetOrderResponse)(nil), // 0: dhhj.dhhj_BetOrderResponse
	(*Dhhj_BonusOptions)(nil),     // 1: dhhj.dhhj_BonusOptions
	(*PorcelainSpread)(nil),       // 2: dhhj.PorcelainSpread
	(*Board)(nil),                 // 3: dhhj.Board
	(*WayWinResult)(nil),          // 4: dhhj.WayWinResult
}
var file_dhhj_proto_depIdxs = []int32{
	3, // 0: dhhj.dhhj_BetOrderResponse.board:type_name -> dhhj.Board
	4, // 1: dhhj.dhhj_BetOrderResponse.winArr:type_name -> dhhj.WayWinResult
	3, // 2: dhhj.dhhj_BetOrderResponse.nextBoard:type_name -> dhhj.Board
	3, // 3: dhhj.dhhj_BetOrderResponse.winGrid:type_name -> dhhj.Board
	3, // 4: dhhj.dhhj_BetOrderResponse.wildEffects:type_name -> dhhj.Board
	1, // 5: dhhj.dhhj_BetOrderResponse.bonusOptions:type_name -> dhhj.dhhj_BonusOptions
	2, // 6: dhhj.dhhj_BetOrderResponse.porcelainSpread:type_name -> dhhj.PorcelainSpread
	3, // 7: dhhj.WayWinResult.grid:type_name -> dhhj.Board
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_dhhj_proto_init() }
func file_dhhj_proto_init() {
	if File_dhhj_proto != nil {
		return
	}
	file_dhhj_proto_msgTypes[0].OneofWrappers = []any{}
	file_dhhj_proto_msgTypes[1].OneofWrappers = []any{}
	file_dhhj_proto_msgTypes[2].OneofWrappers = []any{}
	file_dhhj_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dhhj_proto_rawDesc), len(file_dhhj_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dhhj_proto_goTypes,
		DependencyIndexes: file_dhhj_proto_depIdxs,
		MessageInfos:      file_dhhj_proto_msgTypes,
	}.Build()
	File_dhhj_proto = out.File
	file_dhhj_proto_goTypes = nil
	file_dhhj_proto_depIdxs = nil
}
