// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: yhwy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// yhwy_BetOrderResponse 是单次下注返回给前端的完整结果。
type Yhwy_BetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sn            *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn,omitempty"`                       // 订单号
	Balance       *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`           // 当前余额
	BaseBet       *float64               `protobuf:"fixed64,3,opt,name=baseBet,proto3,oneof" json:"baseBet,omitempty"`           // 基础下注
	Multiplier    *int64                 `protobuf:"varint,4,opt,name=multiplier,proto3,oneof" json:"multiplier,omitempty"`      // 下注倍数
	BetAmount     *float64               `protobuf:"fixed64,5,opt,name=betAmount,proto3,oneof" json:"betAmount,omitempty"`       // 实际投注金额（baseBet × multiplier）
	CurWin        *float64               `protobuf:"fixed64,6,opt,name=curWin,proto3,oneof" json:"curWin,omitempty"`             // step：本次 betOrder 赢分
	RoundWin      *float64               `protobuf:"fixed64,7,opt,name=roundWin,proto3,oneof" json:"roundWin,omitempty"`         // round：本回合累计赢（消除类多步累计）
	TotalWin      *float64               `protobuf:"fixed64,8,opt,name=totalWin,proto3,oneof" json:"totalWin,omitempty"`         // spin：本 spin 总赢（含免费触发轮）
	FreeWin       *float64               `protobuf:"fixed64,9,opt,name=freeWin,proto3,oneof" json:"freeWin,omitempty"`           // 免费局阶段累计总赢（不含触发轮）
	IsRoundOver   *bool                  `protobuf:"varint,10,opt,name=isRoundOver,proto3,oneof" json:"isRoundOver,omitempty"`   // 本 round 是否结束
	CollectLevel  *int64                 `protobuf:"varint,11,opt,name=collectLevel,proto3,oneof" json:"collectLevel,omitempty"` // 当前樱花堆外观等级（0~3）
	IsFree        *bool                  `protobuf:"varint,12,opt,name=isFree,proto3,oneof" json:"isFree,omitempty"`             // 当前是否处于免费游戏
	FreeNum       *int64                 `protobuf:"varint,13,opt,name=freeNum,proto3,oneof" json:"freeNum,omitempty"`           // 剩余免费次数
	FreeTime      *int64                 `protobuf:"varint,14,opt,name=freeTime,proto3,oneof" json:"freeTime,omitempty"`         // 已使用免费次数
	NewFreeTimes  *int64                 `protobuf:"varint,15,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes,omitempty"` // 本步新增的免费旋转次数
	SymGrid       []int64                `protobuf:"varint,16,rep,packed,name=symGrid,proto3" json:"symGrid,omitempty"`          // 牌面
	MysGrid       []int64                `protobuf:"varint,17,rep,packed,name=mysGrid,proto3" json:"mysGrid,omitempty"`          // 百变樱花盘面
	WinGrid       []int64                `protobuf:"varint,18,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`          // 中奖位置网格
	WinArr        []*Yhwy_WinArr         `protobuf:"bytes,19,rep,name=winArr,proto3" json:"winArr,omitempty"`                    // 本次命中的所有中奖线
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Yhwy_BetOrderResponse) Reset() {
	*x = Yhwy_BetOrderResponse{}
	mi := &file_yhwy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yhwy_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yhwy_BetOrderResponse) ProtoMessage() {}

func (x *Yhwy_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yhwy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yhwy_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Yhwy_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_yhwy_proto_rawDescGZIP(), []int{0}
}

func (x *Yhwy_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Yhwy_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetBaseBet() float64 {
	if x != nil && x.BaseBet != nil {
		return *x.BaseBet
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetRoundWin() float64 {
	if x != nil && x.RoundWin != nil {
		return *x.RoundWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetFreeWin() float64 {
	if x != nil && x.FreeWin != nil {
		return *x.FreeWin
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetIsRoundOver() bool {
	if x != nil && x.IsRoundOver != nil {
		return *x.IsRoundOver
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetCollectLevel() int64 {
	if x != nil && x.CollectLevel != nil {
		return *x.CollectLevel
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Yhwy_BetOrderResponse) GetFreeNum() int64 {
	if x != nil && x.FreeNum != nil {
		return *x.FreeNum
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetFreeTime() int64 {
	if x != nil && x.FreeTime != nil {
		return *x.FreeTime
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetNewFreeTimes() int64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

func (x *Yhwy_BetOrderResponse) GetSymGrid() []int64 {
	if x != nil {
		return x.SymGrid
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetMysGrid() []int64 {
	if x != nil {
		return x.MysGrid
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Yhwy_BetOrderResponse) GetWinArr() []*Yhwy_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

type Yhwy_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadNum       *int64                 `protobuf:"varint,1,opt,name=roadNum,proto3,oneof" json:"roadNum,omitempty"` // 中奖线编号，从 0 开始
	Odds          *int64                 `protobuf:"varint,2,opt,name=odds,proto3,oneof" json:"odds,omitempty"`       // 该中奖线赔率
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Yhwy_WinArr) Reset() {
	*x = Yhwy_WinArr{}
	mi := &file_yhwy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yhwy_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yhwy_WinArr) ProtoMessage() {}

func (x *Yhwy_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_yhwy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yhwy_WinArr.ProtoReflect.Descriptor instead.
func (*Yhwy_WinArr) Descriptor() ([]byte, []int) {
	return file_yhwy_proto_rawDescGZIP(), []int{1}
}

func (x *Yhwy_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Yhwy_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

var File_yhwy_proto protoreflect.FileDescriptor

const file_yhwy_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"yhwy.proto\x12\x04yhwy\"\xc2\x06\n" +
	"\x15yhwy_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12\x1d\n" +
	"\abaseBet\x18\x03 \x01(\x01H\x02R\abaseBet\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x03H\x03R\n" +
	"multiplier\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x05 \x01(\x01H\x04R\tbetAmount\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x06 \x01(\x01H\x05R\x06curWin\x88\x01\x01\x12\x1f\n" +
	"\broundWin\x18\a \x01(\x01H\x06R\broundWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\b \x01(\x01H\aR\btotalWin\x88\x01\x01\x12\x1d\n" +
	"\afreeWin\x18\t \x01(\x01H\bR\afreeWin\x88\x01\x01\x12%\n" +
	"\visRoundOver\x18\n" +
	" \x01(\bH\tR\visRoundOver\x88\x01\x01\x12'\n" +
	"\fcollectLevel\x18\v \x01(\x03H\n" +
	"R\fcollectLevel\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\f \x01(\bH\vR\x06isFree\x88\x01\x01\x12\x1d\n" +
	"\afreeNum\x18\r \x01(\x03H\fR\afreeNum\x88\x01\x01\x12\x1f\n" +
	"\bfreeTime\x18\x0e \x01(\x03H\rR\bfreeTime\x88\x01\x01\x12'\n" +
	"\fnewFreeTimes\x18\x0f \x01(\x03H\x0eR\fnewFreeTimes\x88\x01\x01\x12\x18\n" +
	"\asymGrid\x18\x10 \x03(\x03R\asymGrid\x12\x18\n" +
	"\amysGrid\x18\x11 \x03(\x03R\amysGrid\x12\x18\n" +
	"\awinGrid\x18\x12 \x03(\x03R\awinGrid\x12)\n" +
	"\x06winArr\x18\x13 \x03(\v2\x11.yhwy.yhwy_WinArrR\x06winArrB\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\n" +
	"\n" +
	"\b_baseBetB\r\n" +
	"\v_multiplierB\f\n" +
	"\n" +
	"_betAmountB\t\n" +
	"\a_curWinB\v\n" +
	"\t_roundWinB\v\n" +
	"\t_totalWinB\n" +
	"\n" +
	"\b_freeWinB\x0e\n" +
	"\f_isRoundOverB\x0f\n" +
	"\r_collectLevelB\t\n" +
	"\a_isFreeB\n" +
	"\n" +
	"\b_freeNumB\v\n" +
	"\t_freeTimeB\x0f\n" +
	"\r_newFreeTimes\"Z\n" +
	"\vyhwy_WinArr\x12\x1d\n" +
	"\aroadNum\x18\x01 \x01(\x03H\x00R\aroadNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x02 \x01(\x03H\x01R\x04odds\x88\x01\x01B\n" +
	"\n" +
	"\b_roadNumB\a\n" +
	"\x05_oddsB\x19Z\x17egame-grpc/game/yhwy/pbb\x06proto3"

var (
	file_yhwy_proto_rawDescOnce sync.Once
	file_yhwy_proto_rawDescData []byte
)

func file_yhwy_proto_rawDescGZIP() []byte {
	file_yhwy_proto_rawDescOnce.Do(func() {
		file_yhwy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yhwy_proto_rawDesc), len(file_yhwy_proto_rawDesc)))
	})
	return file_yhwy_proto_rawDescData
}

var file_yhwy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yhwy_proto_goTypes = []any{
	(*Yhwy_BetOrderResponse)(nil), // 0: yhwy.yhwy_BetOrderResponse
	(*Yhwy_WinArr)(nil),           // 1: yhwy.yhwy_WinArr
}
var file_yhwy_proto_depIdxs = []int32{
	1, // 0: yhwy.yhwy_BetOrderResponse.winArr:type_name -> yhwy.yhwy_WinArr
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_yhwy_proto_init() }
func file_yhwy_proto_init() {
	if File_yhwy_proto != nil {
		return
	}
	file_yhwy_proto_msgTypes[0].OneofWrappers = []any{}
	file_yhwy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yhwy_proto_rawDesc), len(file_yhwy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yhwy_proto_goTypes,
		DependencyIndexes: file_yhwy_proto_depIdxs,
		MessageInfos:      file_yhwy_proto_msgTypes,
	}.Build()
	File_yhwy_proto = out.File
	file_yhwy_proto_goTypes = nil
	file_yhwy_proto_depIdxs = nil
}
