// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []int64                `protobuf:"varint,1,rep,packed,name=elements,proto3" json:"elements"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetElements() []int64 {
	if x != nil {
		return x.Elements
	}
	return nil
}

// 通用中奖结果
type WinCardType struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Symbol             int32                  `protobuf:"varint,1,opt,name=symbol,proto3" json:"symbol"`                         // 符号
	SymbolCount        int32                  `protobuf:"varint,2,opt,name=symbolCount,proto3" json:"symbolCount"`               // 数量
	LineNumber         *int32                 `protobuf:"varint,3,opt,name=lineNumber,proto3,oneof" json:"lineNumber"`           // 中奖线编号
	BaseLineMultiplier int32                  `protobuf:"varint,4,opt,name=baseLineMultiplier,proto3" json:"baseLineMultiplier"` // 中奖线倍数
	Combo              *int64                 `protobuf:"varint,6,opt,name=combo,proto3,oneof" json:"combo"`                     // 连击倍数
	WinPositions       []int32                `protobuf:"varint,5,rep,packed,name=winPositions,proto3" json:"winPositions"`      // 中奖位置
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WinCardType) Reset() {
	*x = WinCardType{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinCardType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinCardType) ProtoMessage() {}

func (x *WinCardType) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinCardType.ProtoReflect.Descriptor instead.
func (*WinCardType) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *WinCardType) GetSymbol() int32 {
	if x != nil {
		return x.Symbol
	}
	return 0
}

func (x *WinCardType) GetSymbolCount() int32 {
	if x != nil {
		return x.SymbolCount
	}
	return 0
}

func (x *WinCardType) GetLineNumber() int32 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

func (x *WinCardType) GetBaseLineMultiplier() int32 {
	if x != nil {
		return x.BaseLineMultiplier
	}
	return 0
}

func (x *WinCardType) GetCombo() int64 {
	if x != nil && x.Combo != nil {
		return *x.Combo
	}
	return 0
}

func (x *WinCardType) GetWinPositions() []int32 {
	if x != nil {
		return x.WinPositions
	}
	return nil
}

// way 游戏
type WayWinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *int64                 `protobuf:"varint,1,opt,name=symbol,proto3,oneof" json:"symbol"`
	SymbolNum     *int64                 `protobuf:"varint,2,opt,name=symbolNum,proto3,oneof" json:"symbolNum"`
	RoadNum       *int64                 `protobuf:"varint,3,opt,name=roadNum,proto3,oneof" json:"roadNum"`
	Multiplier    *int64                 `protobuf:"varint,4,opt,name=multiplier,proto3,oneof" json:"multiplier"`
	Grid          *Board                 `protobuf:"bytes,5,opt,name=grid,proto3" json:"grid"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WayWinResult) Reset() {
	*x = WayWinResult{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WayWinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WayWinResult) ProtoMessage() {}

func (x *WayWinResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WayWinResult.ProtoReflect.Descriptor instead.
func (*WayWinResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *WayWinResult) GetSymbol() int64 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *WayWinResult) GetSymbolNum() int64 {
	if x != nil && x.SymbolNum != nil {
		return *x.SymbolNum
	}
	return 0
}

func (x *WayWinResult) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *WayWinResult) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *WayWinResult) GetGrid() *Board {
	if x != nil {
		return x.Grid
	}
	return nil
}

// line 游戏
type LineWinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *int64                 `protobuf:"varint,1,opt,name=symbol,proto3,oneof" json:"symbol"`
	SymbolNum     *int64                 `protobuf:"varint,2,opt,name=symbolNum,proto3,oneof" json:"symbolNum"`
	Multiplier    *int64                 `protobuf:"varint,3,opt,name=multiplier,proto3,oneof" json:"multiplier"`
	LineNo        *int64                 `protobuf:"varint,4,opt,name=lineNo,proto3,oneof" json:"lineNo"`
	Grid          *Board                 `protobuf:"bytes,5,opt,name=grid,proto3" json:"grid"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineWinResult) Reset() {
	*x = LineWinResult{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineWinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineWinResult) ProtoMessage() {}

func (x *LineWinResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineWinResult.ProtoReflect.Descriptor instead.
func (*LineWinResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *LineWinResult) GetSymbol() int64 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *LineWinResult) GetSymbolNum() int64 {
	if x != nil && x.SymbolNum != nil {
		return *x.SymbolNum
	}
	return 0
}

func (x *LineWinResult) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *LineWinResult) GetLineNo() int64 {
	if x != nil && x.LineNo != nil {
		return *x.LineNo
	}
	return 0
}

func (x *LineWinResult) GetGrid() *Board {
	if x != nil {
		return x.Grid
	}
	return nil
}

// 连通 游戏
type ConnectWinResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        *int64                 `protobuf:"varint,1,opt,name=symbol,proto3,oneof" json:"symbol"`
	SymbolNum     *int64                 `protobuf:"varint,2,opt,name=symbolNum,proto3,oneof" json:"symbolNum"`
	Multiplier    *int64                 `protobuf:"varint,3,opt,name=multiplier,proto3,oneof" json:"multiplier"`
	Grid          *Board                 `protobuf:"bytes,4,opt,name=grid,proto3" json:"grid"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectWinResult) Reset() {
	*x = ConnectWinResult{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectWinResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectWinResult) ProtoMessage() {}

func (x *ConnectWinResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectWinResult.ProtoReflect.Descriptor instead.
func (*ConnectWinResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectWinResult) GetSymbol() int64 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *ConnectWinResult) GetSymbolNum() int64 {
	if x != nil && x.SymbolNum != nil {
		return *x.SymbolNum
	}
	return 0
}

func (x *ConnectWinResult) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *ConnectWinResult) GetGrid() *Board {
	if x != nil {
		return x.Grid
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\"#\n" +
	"\x05Board\x12\x1a\n" +
	"\belements\x18\x01 \x03(\x03R\belements\"\xf4\x01\n" +
	"\vWinCardType\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\x05R\x06symbol\x12 \n" +
	"\vsymbolCount\x18\x02 \x01(\x05R\vsymbolCount\x12#\n" +
	"\n" +
	"lineNumber\x18\x03 \x01(\x05H\x00R\n" +
	"lineNumber\x88\x01\x01\x12.\n" +
	"\x12baseLineMultiplier\x18\x04 \x01(\x05R\x12baseLineMultiplier\x12\x19\n" +
	"\x05combo\x18\x06 \x01(\x03H\x01R\x05combo\x88\x01\x01\x12\"\n" +
	"\fwinPositions\x18\x05 \x03(\x05R\fwinPositionsB\r\n" +
	"\v_lineNumberB\b\n" +
	"\x06_combo\"\xe9\x01\n" +
	"\fWayWinResult\x12\x1b\n" +
	"\x06symbol\x18\x01 \x01(\x03H\x00R\x06symbol\x88\x01\x01\x12!\n" +
	"\tsymbolNum\x18\x02 \x01(\x03H\x01R\tsymbolNum\x88\x01\x01\x12\x1d\n" +
	"\aroadNum\x18\x03 \x01(\x03H\x02R\aroadNum\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x03H\x03R\n" +
	"multiplier\x88\x01\x01\x12!\n" +
	"\x04grid\x18\x05 \x01(\v2\r.common.BoardR\x04gridB\t\n" +
	"\a_symbolB\f\n" +
	"\n" +
	"_symbolNumB\n" +
	"\n" +
	"\b_roadNumB\r\n" +
	"\v_multiplier\"\xe7\x01\n" +
	"\rLineWinResult\x12\x1b\n" +
	"\x06symbol\x18\x01 \x01(\x03H\x00R\x06symbol\x88\x01\x01\x12!\n" +
	"\tsymbolNum\x18\x02 \x01(\x03H\x01R\tsymbolNum\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x03H\x02R\n" +
	"multiplier\x88\x01\x01\x12\x1b\n" +
	"\x06lineNo\x18\x04 \x01(\x03H\x03R\x06lineNo\x88\x01\x01\x12!\n" +
	"\x04grid\x18\x05 \x01(\v2\r.common.BoardR\x04gridB\t\n" +
	"\a_symbolB\f\n" +
	"\n" +
	"_symbolNumB\r\n" +
	"\v_multiplierB\t\n" +
	"\a_lineNo\"\xc2\x01\n" +
	"\x10ConnectWinResult\x12\x1b\n" +
	"\x06symbol\x18\x01 \x01(\x03H\x00R\x06symbol\x88\x01\x01\x12!\n" +
	"\tsymbolNum\x18\x02 \x01(\x03H\x01R\tsymbolNum\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x03H\x02R\n" +
	"multiplier\x88\x01\x01\x12!\n" +
	"\x04grid\x18\x04 \x01(\v2\r.common.BoardR\x04gridB\t\n" +
	"\a_symbolB\f\n" +
	"\n" +
	"_symbolNumB\r\n" +
	"\v_multiplierB\x1bZ\x19egame-grpc/game/common/pbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_proto_goTypes = []any{
	(*Board)(nil),            // 0: common.Board
	(*WinCardType)(nil),      // 1: common.WinCardType
	(*WayWinResult)(nil),     // 2: common.WayWinResult
	(*LineWinResult)(nil),    // 3: common.LineWinResult
	(*ConnectWinResult)(nil), // 4: common.ConnectWinResult
}
var file_common_proto_depIdxs = []int32{
	0, // 0: common.WayWinResult.grid:type_name -> common.Board
	0, // 1: common.LineWinResult.grid:type_name -> common.Board
	0, // 2: common.ConnectWinResult.grid:type_name -> common.Board
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[1].OneofWrappers = []any{}
	file_common_proto_msgTypes[2].OneofWrappers = []any{}
	file_common_proto_msgTypes[3].OneofWrappers = []any{}
	file_common_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
