// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.19.4
// source: 18922/jqt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 中奖详情响应
type Jqt_BetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSN       *string                `protobuf:"bytes,1,opt,name=orderSN,proto3,oneof" json:"orderSN"`
	Balance       *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance"`
	BetAmount     *float64               `protobuf:"fixed64,3,opt,name=betAmount,proto3,oneof" json:"betAmount"`
	CurrentWin    *float64               `protobuf:"fixed64,4,opt,name=currentWin,proto3,oneof" json:"currentWin"`
	FreeWin       *float64               `protobuf:"fixed64,5,opt,name=freeWin,proto3,oneof" json:"freeWin"`
	TotalWin      *float64               `protobuf:"fixed64,6,opt,name=totalWin,proto3,oneof" json:"totalWin"`
	Free          bool                   `protobuf:"varint,7,opt,name=free,proto3" json:"free"`
	Review        *int64                 `protobuf:"varint,8,opt,name=review,proto3,oneof" json:"review"`
	WinInfo       *Jqt_WinInfo           `protobuf:"bytes,9,opt,name=winInfo,proto3" json:"winInfo"`
	Cards         *Board                 `protobuf:"bytes,10,opt,name=cards,proto3" json:"cards"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jqt_BetOrderResponse) Reset() {
	*x = Jqt_BetOrderResponse{}
	mi := &file__18922_jqt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jqt_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jqt_BetOrderResponse) ProtoMessage() {}

func (x *Jqt_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file__18922_jqt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jqt_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Jqt_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file__18922_jqt_proto_rawDescGZIP(), []int{0}
}

func (x *Jqt_BetOrderResponse) GetOrderSN() string {
	if x != nil && x.OrderSN != nil {
		return *x.OrderSN
	}
	return ""
}

func (x *Jqt_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Jqt_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Jqt_BetOrderResponse) GetCurrentWin() float64 {
	if x != nil && x.CurrentWin != nil {
		return *x.CurrentWin
	}
	return 0
}

func (x *Jqt_BetOrderResponse) GetFreeWin() float64 {
	if x != nil && x.FreeWin != nil {
		return *x.FreeWin
	}
	return 0
}

func (x *Jqt_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Jqt_BetOrderResponse) GetFree() bool {
	if x != nil {
		return x.Free
	}
	return false
}

func (x *Jqt_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Jqt_BetOrderResponse) GetWinInfo() *Jqt_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Jqt_BetOrderResponse) GetCards() *Board {
	if x != nil {
		return x.Cards
	}
	return nil
}

type Jqt_WinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          bool                   `protobuf:"varint,1,opt,name=next,proto3" json:"next"`
	Multi         *int64                 `protobuf:"varint,2,opt,name=multi,proto3,oneof" json:"multi"`
	State         *int64                 `protobuf:"varint,3,opt,name=state,proto3,oneof" json:"state"`
	FreeNum       *int64                 `protobuf:"varint,4,opt,name=freeNum,proto3,oneof" json:"freeNum"`
	FreeTime      *int64                 `protobuf:"varint,5,opt,name=freeTime,proto3,oneof" json:"freeTime"`
	WinArr        []*Jqt_WinArr          `protobuf:"bytes,6,rep,name=winArr,proto3" json:"winArr"`
	MoneyMul      *int64                 `protobuf:"varint,7,opt,name=moneyMul,proto3,oneof" json:"moneyMul"`
	WinGird       *Board                 `protobuf:"bytes,8,opt,name=winGird,proto3" json:"winGird"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jqt_WinInfo) Reset() {
	*x = Jqt_WinInfo{}
	mi := &file__18922_jqt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jqt_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jqt_WinInfo) ProtoMessage() {}

func (x *Jqt_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file__18922_jqt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jqt_WinInfo.ProtoReflect.Descriptor instead.
func (*Jqt_WinInfo) Descriptor() ([]byte, []int) {
	return file__18922_jqt_proto_rawDescGZIP(), []int{1}
}

func (x *Jqt_WinInfo) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *Jqt_WinInfo) GetMulti() int64 {
	if x != nil && x.Multi != nil {
		return *x.Multi
	}
	return 0
}

func (x *Jqt_WinInfo) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Jqt_WinInfo) GetFreeNum() int64 {
	if x != nil && x.FreeNum != nil {
		return *x.FreeNum
	}
	return 0
}

func (x *Jqt_WinInfo) GetFreeTime() int64 {
	if x != nil && x.FreeTime != nil {
		return *x.FreeTime
	}
	return 0
}

func (x *Jqt_WinInfo) GetWinArr() []*Jqt_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Jqt_WinInfo) GetMoneyMul() int64 {
	if x != nil && x.MoneyMul != nil {
		return *x.MoneyMul
	}
	return 0
}

func (x *Jqt_WinInfo) GetWinGird() *Board {
	if x != nil {
		return x.WinGird
	}
	return nil
}

type Jqt_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Val           *int64                 `protobuf:"varint,1,opt,name=val,proto3,oneof" json:"val"`
	RoadNum       *int64                 `protobuf:"varint,2,opt,name=roadNum,proto3,oneof" json:"roadNum"`
	StarNum       *int64                 `protobuf:"varint,3,opt,name=starNum,proto3,oneof" json:"starNum"`
	Odds          *int64                 `protobuf:"varint,4,opt,name=odds,proto3,oneof" json:"odds"`
	Mul           *int64                 `protobuf:"varint,5,opt,name=mul,proto3,oneof" json:"mul"`
	LineNo        *int64                 `protobuf:"varint,6,opt,name=lineNo,proto3,oneof" json:"lineNo"`
	Grid          *Board                 `protobuf:"bytes,7,opt,name=grid,proto3" json:"grid"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jqt_WinArr) Reset() {
	*x = Jqt_WinArr{}
	mi := &file__18922_jqt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jqt_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jqt_WinArr) ProtoMessage() {}

func (x *Jqt_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file__18922_jqt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jqt_WinArr.ProtoReflect.Descriptor instead.
func (*Jqt_WinArr) Descriptor() ([]byte, []int) {
	return file__18922_jqt_proto_rawDescGZIP(), []int{2}
}

func (x *Jqt_WinArr) GetVal() int64 {
	if x != nil && x.Val != nil {
		return *x.Val
	}
	return 0
}

func (x *Jqt_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Jqt_WinArr) GetStarNum() int64 {
	if x != nil && x.StarNum != nil {
		return *x.StarNum
	}
	return 0
}

func (x *Jqt_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

func (x *Jqt_WinArr) GetMul() int64 {
	if x != nil && x.Mul != nil {
		return *x.Mul
	}
	return 0
}

func (x *Jqt_WinArr) GetLineNo() int64 {
	if x != nil && x.LineNo != nil {
		return *x.LineNo
	}
	return 0
}

func (x *Jqt_WinArr) GetGrid() *Board {
	if x != nil {
		return x.Grid
	}
	return nil
}

var File__18922_jqt_proto protoreflect.FileDescriptor

const file__18922_jqt_proto_rawDesc = "" +
	"\n" +
	"\x0f18922/jqt.proto\x12\x03jqt\x1a\fcommon.proto\"\xb7\x03\n" +
	"\x14jqt_BetOrderResponse\x12\x1d\n" +
	"\aorderSN\x18\x01 \x01(\tH\x00R\aorderSN\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x03 \x01(\x01H\x02R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"currentWin\x18\x04 \x01(\x01H\x03R\n" +
	"currentWin\x88\x01\x01\x12\x1d\n" +
	"\afreeWin\x18\x05 \x01(\x01H\x04R\afreeWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\x06 \x01(\x01H\x05R\btotalWin\x88\x01\x01\x12\x12\n" +
	"\x04free\x18\a \x01(\bR\x04free\x12\x1b\n" +
	"\x06review\x18\b \x01(\x03H\x06R\x06review\x88\x01\x01\x12*\n" +
	"\awinInfo\x18\t \x01(\v2\x10.jqt.jqt_WinInfoR\awinInfo\x12#\n" +
	"\x05cards\x18\n" +
	" \x01(\v2\r.common.BoardR\x05cardsB\n" +
	"\n" +
	"\b_orderSNB\n" +
	"\n" +
	"\b_balanceB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_currentWinB\n" +
	"\n" +
	"\b_freeWinB\v\n" +
	"\t_totalWinB\t\n" +
	"\a_review\"\xc4\x02\n" +
	"\vjqt_WinInfo\x12\x12\n" +
	"\x04next\x18\x01 \x01(\bR\x04next\x12\x19\n" +
	"\x05multi\x18\x02 \x01(\x03H\x00R\x05multi\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x03 \x01(\x03H\x01R\x05state\x88\x01\x01\x12\x1d\n" +
	"\afreeNum\x18\x04 \x01(\x03H\x02R\afreeNum\x88\x01\x01\x12\x1f\n" +
	"\bfreeTime\x18\x05 \x01(\x03H\x03R\bfreeTime\x88\x01\x01\x12'\n" +
	"\x06winArr\x18\x06 \x03(\v2\x0f.jqt.jqt_WinArrR\x06winArr\x12\x1f\n" +
	"\bmoneyMul\x18\a \x01(\x03H\x04R\bmoneyMul\x88\x01\x01\x12'\n" +
	"\awinGird\x18\b \x01(\v2\r.common.BoardR\awinGirdB\b\n" +
	"\x06_multiB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_freeNumB\v\n" +
	"\t_freeTimeB\v\n" +
	"\t_moneyMul\"\x8d\x02\n" +
	"\n" +
	"jqt_WinArr\x12\x15\n" +
	"\x03val\x18\x01 \x01(\x03H\x00R\x03val\x88\x01\x01\x12\x1d\n" +
	"\aroadNum\x18\x02 \x01(\x03H\x01R\aroadNum\x88\x01\x01\x12\x1d\n" +
	"\astarNum\x18\x03 \x01(\x03H\x02R\astarNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x04 \x01(\x03H\x03R\x04odds\x88\x01\x01\x12\x15\n" +
	"\x03mul\x18\x05 \x01(\x03H\x04R\x03mul\x88\x01\x01\x12\x1b\n" +
	"\x06lineNo\x18\x06 \x01(\x03H\x05R\x06lineNo\x88\x01\x01\x12!\n" +
	"\x04grid\x18\a \x01(\v2\r.common.BoardR\x04gridB\x06\n" +
	"\x04_valB\n" +
	"\n" +
	"\b_roadNumB\n" +
	"\n" +
	"\b_starNumB\a\n" +
	"\x05_oddsB\x06\n" +
	"\x04_mulB\t\n" +
	"\a_lineNoB\x1bZ\x19egame-grpc/game/common/pbb\x06proto3"

var (
	file__18922_jqt_proto_rawDescOnce sync.Once
	file__18922_jqt_proto_rawDescData []byte
)

func file__18922_jqt_proto_rawDescGZIP() []byte {
	file__18922_jqt_proto_rawDescOnce.Do(func() {
		file__18922_jqt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file__18922_jqt_proto_rawDesc), len(file__18922_jqt_proto_rawDesc)))
	})
	return file__18922_jqt_proto_rawDescData
}

var file__18922_jqt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file__18922_jqt_proto_goTypes = []any{
	(*Jqt_BetOrderResponse)(nil), // 0: jqt.jqt_BetOrderResponse
	(*Jqt_WinInfo)(nil),          // 1: jqt.jqt_WinInfo
	(*Jqt_WinArr)(nil),           // 2: jqt.jqt_WinArr
	(*Board)(nil),                // 3: common.Board
}
var file__18922_jqt_proto_depIdxs = []int32{
	1, // 0: jqt.jqt_BetOrderResponse.winInfo:type_name -> jqt.jqt_WinInfo
	3, // 1: jqt.jqt_BetOrderResponse.cards:type_name -> common.Board
	2, // 2: jqt.jqt_WinInfo.winArr:type_name -> jqt.jqt_WinArr
	3, // 3: jqt.jqt_WinInfo.winGird:type_name -> common.Board
	3, // 4: jqt.jqt_WinArr.grid:type_name -> common.Board
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file__18922_jqt_proto_init() }
func file__18922_jqt_proto_init() {
	if File__18922_jqt_proto != nil {
		return
	}
	file_common_proto_init()
	file__18922_jqt_proto_msgTypes[0].OneofWrappers = []any{}
	file__18922_jqt_proto_msgTypes[1].OneofWrappers = []any{}
	file__18922_jqt_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file__18922_jqt_proto_rawDesc), len(file__18922_jqt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file__18922_jqt_proto_goTypes,
		DependencyIndexes: file__18922_jqt_proto_depIdxs,
		MessageInfos:      file__18922_jqt_proto_msgTypes,
	}.Build()
	File__18922_jqt_proto = out.File
	file__18922_jqt_proto_goTypes = nil
	file__18922_jqt_proto_depIdxs = nil
}
