// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: 18979/mdsdbz.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 中奖详情响应
type Mdsdbz_BetOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderSn        *string                `protobuf:"bytes,1,opt,name=orderSn,proto3,oneof" json:"orderSn"`                 // 订单号
	Balance        *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance"`               // 余额
	BetAmount      *float64               `protobuf:"fixed64,3,opt,name=betAmount,proto3,oneof" json:"betAmount"`           // 投注金额
	CurrentWin     *float64               `protobuf:"fixed64,4,opt,name=currentWin,proto3,oneof" json:"currentWin"`         // 当前赢分
	RoundWin       *float64               `protobuf:"fixed64,5,opt,name=roundWin,proto3,oneof" json:"roundWin"`             // 当前round赢
	FreeTotalMoney *float64               `protobuf:"fixed64,6,opt,name=freeTotalMoney,proto3,oneof" json:"freeTotalMoney"` // 免费游戏总金额
	TotalWin       *float64               `protobuf:"fixed64,7,opt,name=totalWin,proto3,oneof" json:"totalWin"`             // 总赢分
	IsFree         *bool                  `protobuf:"varint,8,opt,name=isFree,proto3,oneof" json:"isFree"`                  // 是否免费游戏
	Review         *int64                 `protobuf:"varint,9,opt,name=review,proto3,oneof" json:"review"`                  // 审核状态
	WinInfo        *Mdsdbz_WinInfo        `protobuf:"bytes,10,opt,name=winInfo,proto3" json:"winInfo"`                      // 赢分详情
	SymGrid        *Board                 `protobuf:"bytes,11,opt,name=symGrid,proto3" json:"symGrid"`                      // 牌面
	RemFCot        *uint64                `protobuf:"varint,12,opt,name=remFCot,proto3,oneof" json:"remFCot"`               // 免费剩余次数
	SpinOver       *bool                  `protobuf:"varint,13,opt,name=spinOver,proto3,oneof" json:"spinOver"`             // 回合是否结束
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Mdsdbz_BetOrderResponse) Reset() {
	*x = Mdsdbz_BetOrderResponse{}
	mi := &file__18979_mdsdbz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mdsdbz_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mdsdbz_BetOrderResponse) ProtoMessage() {}

func (x *Mdsdbz_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file__18979_mdsdbz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mdsdbz_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Mdsdbz_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file__18979_mdsdbz_proto_rawDescGZIP(), []int{0}
}

func (x *Mdsdbz_BetOrderResponse) GetOrderSn() string {
	if x != nil && x.OrderSn != nil {
		return *x.OrderSn
	}
	return ""
}

func (x *Mdsdbz_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Mdsdbz_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Mdsdbz_BetOrderResponse) GetCurrentWin() float64 {
	if x != nil && x.CurrentWin != nil {
		return *x.CurrentWin
	}
	return 0
}

func (x *Mdsdbz_BetOrderResponse) GetRoundWin() float64 {
	if x != nil && x.RoundWin != nil {
		return *x.RoundWin
	}
	return 0
}

func (x *Mdsdbz_BetOrderResponse) GetFreeTotalMoney() float64 {
	if x != nil && x.FreeTotalMoney != nil {
		return *x.FreeTotalMoney
	}
	return 0
}

func (x *Mdsdbz_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Mdsdbz_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Mdsdbz_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Mdsdbz_BetOrderResponse) GetWinInfo() *Mdsdbz_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Mdsdbz_BetOrderResponse) GetSymGrid() *Board {
	if x != nil {
		return x.SymGrid
	}
	return nil
}

func (x *Mdsdbz_BetOrderResponse) GetRemFCot() uint64 {
	if x != nil && x.RemFCot != nil {
		return *x.RemFCot
	}
	return 0
}

func (x *Mdsdbz_BetOrderResponse) GetSpinOver() bool {
	if x != nil && x.SpinOver != nil {
		return *x.SpinOver
	}
	return false
}

type Mdsdbz_WinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *int64                 `protobuf:"varint,1,opt,name=state,proto3,oneof" json:"state"`       // 状态
	WinArr        []*Mdsdbz_WinArr       `protobuf:"bytes,2,rep,name=winArr,proto3" json:"winArr"`            // 中奖详细信息
	WinGird       *Board                 `protobuf:"bytes,3,opt,name=winGird,proto3" json:"winGird"`          // 中奖网格
	OrigGrid      *Board                 `protobuf:"bytes,4,opt,name=origGrid,proto3" json:"origGrid"`        // 原始牌面
	LineMult      *int64                 `protobuf:"varint,5,opt,name=lineMult,proto3,oneof" json:"lineMult"` // 线倍数
	StepMult      *int64                 `protobuf:"varint,6,opt,name=stepMult,proto3,oneof" json:"stepMult"` // 总倍数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mdsdbz_WinInfo) Reset() {
	*x = Mdsdbz_WinInfo{}
	mi := &file__18979_mdsdbz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mdsdbz_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mdsdbz_WinInfo) ProtoMessage() {}

func (x *Mdsdbz_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file__18979_mdsdbz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mdsdbz_WinInfo.ProtoReflect.Descriptor instead.
func (*Mdsdbz_WinInfo) Descriptor() ([]byte, []int) {
	return file__18979_mdsdbz_proto_rawDescGZIP(), []int{1}
}

func (x *Mdsdbz_WinInfo) GetState() int64 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *Mdsdbz_WinInfo) GetWinArr() []*Mdsdbz_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Mdsdbz_WinInfo) GetWinGird() *Board {
	if x != nil {
		return x.WinGird
	}
	return nil
}

func (x *Mdsdbz_WinInfo) GetOrigGrid() *Board {
	if x != nil {
		return x.OrigGrid
	}
	return nil
}

func (x *Mdsdbz_WinInfo) GetLineMult() int64 {
	if x != nil && x.LineMult != nil {
		return *x.LineMult
	}
	return 0
}

func (x *Mdsdbz_WinInfo) GetStepMult() int64 {
	if x != nil && x.StepMult != nil {
		return *x.StepMult
	}
	return 0
}

type Mdsdbz_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sym           *int64                 `protobuf:"varint,1,opt,name=sym,proto3,oneof" json:"sym"`         // 中奖符号
	Scnt          *int64                 `protobuf:"varint,2,opt,name=scnt,proto3,oneof" json:"scnt"`       // 数量
	Lcnt          *int64                 `protobuf:"varint,3,opt,name=lcnt,proto3,oneof" json:"lcnt"`       // 中奖线
	WlMu          *int64                 `protobuf:"varint,4,opt,name=wlMu,proto3,oneof" json:"wlMu"`       // 百搭倍数
	BaseMu        *int64                 `protobuf:"varint,5,opt,name=baseMu,proto3,oneof" json:"baseMu"`   // 倍数
	TotalMu       *int64                 `protobuf:"varint,6,opt,name=totalMu,proto3,oneof" json:"totalMu"` // 总倍数倍数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mdsdbz_WinArr) Reset() {
	*x = Mdsdbz_WinArr{}
	mi := &file__18979_mdsdbz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mdsdbz_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mdsdbz_WinArr) ProtoMessage() {}

func (x *Mdsdbz_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file__18979_mdsdbz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mdsdbz_WinArr.ProtoReflect.Descriptor instead.
func (*Mdsdbz_WinArr) Descriptor() ([]byte, []int) {
	return file__18979_mdsdbz_proto_rawDescGZIP(), []int{2}
}

func (x *Mdsdbz_WinArr) GetSym() int64 {
	if x != nil && x.Sym != nil {
		return *x.Sym
	}
	return 0
}

func (x *Mdsdbz_WinArr) GetScnt() int64 {
	if x != nil && x.Scnt != nil {
		return *x.Scnt
	}
	return 0
}

func (x *Mdsdbz_WinArr) GetLcnt() int64 {
	if x != nil && x.Lcnt != nil {
		return *x.Lcnt
	}
	return 0
}

func (x *Mdsdbz_WinArr) GetWlMu() int64 {
	if x != nil && x.WlMu != nil {
		return *x.WlMu
	}
	return 0
}

func (x *Mdsdbz_WinArr) GetBaseMu() int64 {
	if x != nil && x.BaseMu != nil {
		return *x.BaseMu
	}
	return 0
}

func (x *Mdsdbz_WinArr) GetTotalMu() int64 {
	if x != nil && x.TotalMu != nil {
		return *x.TotalMu
	}
	return 0
}

var File__18979_mdsdbz_proto protoreflect.FileDescriptor

const file__18979_mdsdbz_proto_rawDesc = "" +
	"\n" +
	"\x1218979/mdsdbz.proto\x12\x06mdsdbz\x1a\fcommon.proto\"\xf4\x04\n" +
	"\x17mdsdbz_BetOrderResponse\x12\x1d\n" +
	"\aorderSn\x18\x01 \x01(\tH\x00R\aorderSn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x03 \x01(\x01H\x02R\tbetAmount\x88\x01\x01\x12#\n" +
	"\n" +
	"currentWin\x18\x04 \x01(\x01H\x03R\n" +
	"currentWin\x88\x01\x01\x12\x1f\n" +
	"\broundWin\x18\x05 \x01(\x01H\x04R\broundWin\x88\x01\x01\x12+\n" +
	"\x0efreeTotalMoney\x18\x06 \x01(\x01H\x05R\x0efreeTotalMoney\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\a \x01(\x01H\x06R\btotalWin\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\b \x01(\bH\aR\x06isFree\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\t \x01(\x03H\bR\x06review\x88\x01\x01\x120\n" +
	"\awinInfo\x18\n" +
	" \x01(\v2\x16.mdsdbz.mdsdbz_WinInfoR\awinInfo\x12'\n" +
	"\asymGrid\x18\v \x01(\v2\r.common.BoardR\asymGrid\x12\x1d\n" +
	"\aremFCot\x18\f \x01(\x04H\tR\aremFCot\x88\x01\x01\x12\x1f\n" +
	"\bspinOver\x18\r \x01(\bH\n" +
	"R\bspinOver\x88\x01\x01B\n" +
	"\n" +
	"\b_orderSnB\n" +
	"\n" +
	"\b_balanceB\f\n" +
	"\n" +
	"_betAmountB\r\n" +
	"\v_currentWinB\v\n" +
	"\t_roundWinB\x11\n" +
	"\x0f_freeTotalMoneyB\v\n" +
	"\t_totalWinB\t\n" +
	"\a_isFreeB\t\n" +
	"\a_reviewB\n" +
	"\n" +
	"\b_remFCotB\v\n" +
	"\t_spinOver\"\x94\x02\n" +
	"\x0emdsdbz_WinInfo\x12\x19\n" +
	"\x05state\x18\x01 \x01(\x03H\x00R\x05state\x88\x01\x01\x12-\n" +
	"\x06winArr\x18\x02 \x03(\v2\x15.mdsdbz.mdsdbz_WinArrR\x06winArr\x12'\n" +
	"\awinGird\x18\x03 \x01(\v2\r.common.BoardR\awinGird\x12)\n" +
	"\borigGrid\x18\x04 \x01(\v2\r.common.BoardR\borigGrid\x12\x1f\n" +
	"\blineMult\x18\x05 \x01(\x03H\x01R\blineMult\x88\x01\x01\x12\x1f\n" +
	"\bstepMult\x18\x06 \x01(\x03H\x02R\bstepMult\x88\x01\x01B\b\n" +
	"\x06_stateB\v\n" +
	"\t_lineMultB\v\n" +
	"\t_stepMult\"\xe7\x01\n" +
	"\rmdsdbz_WinArr\x12\x15\n" +
	"\x03sym\x18\x01 \x01(\x03H\x00R\x03sym\x88\x01\x01\x12\x17\n" +
	"\x04scnt\x18\x02 \x01(\x03H\x01R\x04scnt\x88\x01\x01\x12\x17\n" +
	"\x04lcnt\x18\x03 \x01(\x03H\x02R\x04lcnt\x88\x01\x01\x12\x17\n" +
	"\x04wlMu\x18\x04 \x01(\x03H\x03R\x04wlMu\x88\x01\x01\x12\x1b\n" +
	"\x06baseMu\x18\x05 \x01(\x03H\x04R\x06baseMu\x88\x01\x01\x12\x1d\n" +
	"\atotalMu\x18\x06 \x01(\x03H\x05R\atotalMu\x88\x01\x01B\x06\n" +
	"\x04_symB\a\n" +
	"\x05_scntB\a\n" +
	"\x05_lcntB\a\n" +
	"\x05_wlMuB\t\n" +
	"\a_baseMuB\n" +
	"\n" +
	"\b_totalMuB\x1bZ\x19egame-grpc/game/common/pbb\x06proto3"

var (
	file__18979_mdsdbz_proto_rawDescOnce sync.Once
	file__18979_mdsdbz_proto_rawDescData []byte
)

func file__18979_mdsdbz_proto_rawDescGZIP() []byte {
	file__18979_mdsdbz_proto_rawDescOnce.Do(func() {
		file__18979_mdsdbz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file__18979_mdsdbz_proto_rawDesc), len(file__18979_mdsdbz_proto_rawDesc)))
	})
	return file__18979_mdsdbz_proto_rawDescData
}

var file__18979_mdsdbz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file__18979_mdsdbz_proto_goTypes = []any{
	(*Mdsdbz_BetOrderResponse)(nil), // 0: mdsdbz.mdsdbz_BetOrderResponse
	(*Mdsdbz_WinInfo)(nil),          // 1: mdsdbz.mdsdbz_WinInfo
	(*Mdsdbz_WinArr)(nil),           // 2: mdsdbz.mdsdbz_WinArr
	(*Board)(nil),                   // 3: common.Board
}
var file__18979_mdsdbz_proto_depIdxs = []int32{
	1, // 0: mdsdbz.mdsdbz_BetOrderResponse.winInfo:type_name -> mdsdbz.mdsdbz_WinInfo
	3, // 1: mdsdbz.mdsdbz_BetOrderResponse.symGrid:type_name -> common.Board
	2, // 2: mdsdbz.mdsdbz_WinInfo.winArr:type_name -> mdsdbz.mdsdbz_WinArr
	3, // 3: mdsdbz.mdsdbz_WinInfo.winGird:type_name -> common.Board
	3, // 4: mdsdbz.mdsdbz_WinInfo.origGrid:type_name -> common.Board
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file__18979_mdsdbz_proto_init() }
func file__18979_mdsdbz_proto_init() {
	if File__18979_mdsdbz_proto != nil {
		return
	}
	file_common_proto_init()
	file__18979_mdsdbz_proto_msgTypes[0].OneofWrappers = []any{}
	file__18979_mdsdbz_proto_msgTypes[1].OneofWrappers = []any{}
	file__18979_mdsdbz_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file__18979_mdsdbz_proto_rawDesc), len(file__18979_mdsdbz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file__18979_mdsdbz_proto_goTypes,
		DependencyIndexes: file__18979_mdsdbz_proto_depIdxs,
		MessageInfos:      file__18979_mdsdbz_proto_msgTypes,
	}.Build()
	File__18979_mdsdbz_proto = out.File
	file__18979_mdsdbz_proto_goTypes = nil
	file__18979_mdsdbz_proto_depIdxs = nil
}
