// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sjxj.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sjxj_BetOrderResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Sn                 *string                `protobuf:"bytes,1,opt,name=sn,proto3,oneof" json:"sn,omitempty"`                                   // 订单号
	Balance            *float64               `protobuf:"fixed64,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`                       // 玩家当前余额
	BaseBet            *float64               `protobuf:"fixed64,3,opt,name=baseBet,proto3,oneof" json:"baseBet,omitempty"`                       // 基础下注
	Multiplier         *int64                 `protobuf:"varint,4,opt,name=multiplier,proto3,oneof" json:"multiplier,omitempty"`                  // 下注倍数
	BetAmount          *float64               `protobuf:"fixed64,5,opt,name=betAmount,proto3,oneof" json:"betAmount,omitempty"`                   // 本局下注金额 (baseMoney * multiple * 50)
	CurWin             *float64               `protobuf:"fixed64,6,opt,name=curWin,proto3,oneof" json:"curWin,omitempty"`                         // 本局赢取金额
	FreeTotalWin       *float64               `protobuf:"fixed64,7,opt,name=freeTotalWin,proto3,oneof" json:"freeTotalWin,omitempty"`             // 免费游戏累计赢取
	TotalWin           *float64               `protobuf:"fixed64,8,opt,name=totalWin,proto3,oneof" json:"totalWin,omitempty"`                     // 本回合总赢取
	IsFree             *bool                  `protobuf:"varint,9,opt,name=isFree,proto3,oneof" json:"isFree,omitempty"`                          // 是否处于免费模式
	Review             *int64                 `protobuf:"varint,10,opt,name=review,proto3,oneof" json:"review,omitempty"`                         // 复盘标志 1=复盘 0=正常
	WinInfo            *Sjxj_WinInfo          `protobuf:"bytes,11,opt,name=winInfo,proto3" json:"winInfo,omitempty"`                              // 中奖详情（线奖列表、加次等）
	Cards              []int64                `protobuf:"varint,12,rep,packed,name=cards,proto3" json:"cards,omitempty"`                          // 符号网格 8×5，按行优先 elements共40个（服务端方向，不翻转）
	RemainingFreeTimes *int64                 `protobuf:"varint,13,opt,name=remainingFreeTimes,proto3,oneof" json:"remainingFreeTimes,omitempty"` // 剩余免费次数
	TotalFreeTimes     *int64                 `protobuf:"varint,14,opt,name=totalFreeTimes,proto3,oneof" json:"totalFreeTimes,omitempty"`         // 已使用免费次数
	WinGrid            []int64                `protobuf:"varint,15,rep,packed,name=winGrid,proto3" json:"winGrid,omitempty"`                      // 中奖位置网格 8×5（仅标记底4行，1=中奖位 0=未中奖）
	NewFreeTimes       *int64                 `protobuf:"varint,16,opt,name=newFreeTimes,proto3,oneof" json:"newFreeTimes,omitempty"`             // 新增免费次数
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Sjxj_BetOrderResponse) Reset() {
	*x = Sjxj_BetOrderResponse{}
	mi := &file_sjxj_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sjxj_BetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sjxj_BetOrderResponse) ProtoMessage() {}

func (x *Sjxj_BetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sjxj_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sjxj_BetOrderResponse.ProtoReflect.Descriptor instead.
func (*Sjxj_BetOrderResponse) Descriptor() ([]byte, []int) {
	return file_sjxj_proto_rawDescGZIP(), []int{0}
}

func (x *Sjxj_BetOrderResponse) GetSn() string {
	if x != nil && x.Sn != nil {
		return *x.Sn
	}
	return ""
}

func (x *Sjxj_BetOrderResponse) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetBaseBet() float64 {
	if x != nil && x.BaseBet != nil {
		return *x.BaseBet
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetMultiplier() int64 {
	if x != nil && x.Multiplier != nil {
		return *x.Multiplier
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetBetAmount() float64 {
	if x != nil && x.BetAmount != nil {
		return *x.BetAmount
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetCurWin() float64 {
	if x != nil && x.CurWin != nil {
		return *x.CurWin
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetFreeTotalWin() float64 {
	if x != nil && x.FreeTotalWin != nil {
		return *x.FreeTotalWin
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetTotalWin() float64 {
	if x != nil && x.TotalWin != nil {
		return *x.TotalWin
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetIsFree() bool {
	if x != nil && x.IsFree != nil {
		return *x.IsFree
	}
	return false
}

func (x *Sjxj_BetOrderResponse) GetReview() int64 {
	if x != nil && x.Review != nil {
		return *x.Review
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetWinInfo() *Sjxj_WinInfo {
	if x != nil {
		return x.WinInfo
	}
	return nil
}

func (x *Sjxj_BetOrderResponse) GetCards() []int64 {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *Sjxj_BetOrderResponse) GetRemainingFreeTimes() int64 {
	if x != nil && x.RemainingFreeTimes != nil {
		return *x.RemainingFreeTimes
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetTotalFreeTimes() int64 {
	if x != nil && x.TotalFreeTimes != nil {
		return *x.TotalFreeTimes
	}
	return 0
}

func (x *Sjxj_BetOrderResponse) GetWinGrid() []int64 {
	if x != nil {
		return x.WinGrid
	}
	return nil
}

func (x *Sjxj_BetOrderResponse) GetNewFreeTimes() int64 {
	if x != nil && x.NewFreeTimes != nil {
		return *x.NewFreeTimes
	}
	return 0
}

// sgz_WinInfo 中奖详情
type Sjxj_WinInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinArr        []*Sjxj_WinArr         `protobuf:"bytes,1,rep,name=winArr,proto3" json:"winArr,omitempty"`                     // 本步各条中奖线的详情
	FreeUnlockTh  []int64                `protobuf:"varint,2,rep,packed,name=freeUnlockTh,proto3" json:"freeUnlockTh,omitempty"` // 免费剩余解锁行数量
	ScatterMul    []int64                `protobuf:"varint,3,rep,packed,name=scatterMul,proto3" json:"scatterMul,omitempty"`     // 夺宝符号倍数列表（一维数组）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sjxj_WinInfo) Reset() {
	*x = Sjxj_WinInfo{}
	mi := &file_sjxj_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sjxj_WinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sjxj_WinInfo) ProtoMessage() {}

func (x *Sjxj_WinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sjxj_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sjxj_WinInfo.ProtoReflect.Descriptor instead.
func (*Sjxj_WinInfo) Descriptor() ([]byte, []int) {
	return file_sjxj_proto_rawDescGZIP(), []int{1}
}

func (x *Sjxj_WinInfo) GetWinArr() []*Sjxj_WinArr {
	if x != nil {
		return x.WinArr
	}
	return nil
}

func (x *Sjxj_WinInfo) GetFreeUnlockTh() []int64 {
	if x != nil {
		return x.FreeUnlockTh
	}
	return nil
}

func (x *Sjxj_WinInfo) GetScatterMul() []int64 {
	if x != nil {
		return x.ScatterMul
	}
	return nil
}

// sgz_WinArr 单条中奖线详情
type Sjxj_WinArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoadNum       *int64                 `protobuf:"varint,1,opt,name=roadNum,proto3,oneof" json:"roadNum,omitempty"` // 支付线编号 0~19
	Odds          *int64                 `protobuf:"varint,2,opt,name=odds,proto3,oneof" json:"odds,omitempty"`       // 基础赔率 来自 pay_table
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sjxj_WinArr) Reset() {
	*x = Sjxj_WinArr{}
	mi := &file_sjxj_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sjxj_WinArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sjxj_WinArr) ProtoMessage() {}

func (x *Sjxj_WinArr) ProtoReflect() protoreflect.Message {
	mi := &file_sjxj_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sjxj_WinArr.ProtoReflect.Descriptor instead.
func (*Sjxj_WinArr) Descriptor() ([]byte, []int) {
	return file_sjxj_proto_rawDescGZIP(), []int{2}
}

func (x *Sjxj_WinArr) GetRoadNum() int64 {
	if x != nil && x.RoadNum != nil {
		return *x.RoadNum
	}
	return 0
}

func (x *Sjxj_WinArr) GetOdds() int64 {
	if x != nil && x.Odds != nil {
		return *x.Odds
	}
	return 0
}

var File_sjxj_proto protoreflect.FileDescriptor

const file_sjxj_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sjxj.proto\x12\x04sjxj\"\xf2\x05\n" +
	"\x15sjxj_BetOrderResponse\x12\x13\n" +
	"\x02sn\x18\x01 \x01(\tH\x00R\x02sn\x88\x01\x01\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x01H\x01R\abalance\x88\x01\x01\x12\x1d\n" +
	"\abaseBet\x18\x03 \x01(\x01H\x02R\abaseBet\x88\x01\x01\x12#\n" +
	"\n" +
	"multiplier\x18\x04 \x01(\x03H\x03R\n" +
	"multiplier\x88\x01\x01\x12!\n" +
	"\tbetAmount\x18\x05 \x01(\x01H\x04R\tbetAmount\x88\x01\x01\x12\x1b\n" +
	"\x06curWin\x18\x06 \x01(\x01H\x05R\x06curWin\x88\x01\x01\x12'\n" +
	"\ffreeTotalWin\x18\a \x01(\x01H\x06R\ffreeTotalWin\x88\x01\x01\x12\x1f\n" +
	"\btotalWin\x18\b \x01(\x01H\aR\btotalWin\x88\x01\x01\x12\x1b\n" +
	"\x06isFree\x18\t \x01(\bH\bR\x06isFree\x88\x01\x01\x12\x1b\n" +
	"\x06review\x18\n" +
	" \x01(\x03H\tR\x06review\x88\x01\x01\x12,\n" +
	"\awinInfo\x18\v \x01(\v2\x12.sjxj.sjxj_WinInfoR\awinInfo\x12\x14\n" +
	"\x05cards\x18\f \x03(\x03R\x05cards\x123\n" +
	"\x12remainingFreeTimes\x18\r \x01(\x03H\n" +
	"R\x12remainingFreeTimes\x88\x01\x01\x12+\n" +
	"\x0etotalFreeTimes\x18\x0e \x01(\x03H\vR\x0etotalFreeTimes\x88\x01\x01\x12\x18\n" +
	"\awinGrid\x18\x0f \x03(\x03R\awinGrid\x12'\n" +
	"\fnewFreeTimes\x18\x10 \x01(\x03H\fR\fnewFreeTimes\x88\x01\x01B\x05\n" +
	"\x03_snB\n" +
	"\n" +
	"\b_balanceB\n" +
	"\n" +
	"\b_baseBetB\r\n" +
	"\v_multiplierB\f\n" +
	"\n" +
	"_betAmountB\t\n" +
	"\a_curWinB\x0f\n" +
	"\r_freeTotalWinB\v\n" +
	"\t_totalWinB\t\n" +
	"\a_isFreeB\t\n" +
	"\a_reviewB\x15\n" +
	"\x13_remainingFreeTimesB\x11\n" +
	"\x0f_totalFreeTimesB\x0f\n" +
	"\r_newFreeTimes\"}\n" +
	"\fsjxj_WinInfo\x12)\n" +
	"\x06winArr\x18\x01 \x03(\v2\x11.sjxj.sjxj_WinArrR\x06winArr\x12\"\n" +
	"\ffreeUnlockTh\x18\x02 \x03(\x03R\ffreeUnlockTh\x12\x1e\n" +
	"\n" +
	"scatterMul\x18\x03 \x03(\x03R\n" +
	"scatterMul\"Z\n" +
	"\vsjxj_WinArr\x12\x1d\n" +
	"\aroadNum\x18\x01 \x01(\x03H\x00R\aroadNum\x88\x01\x01\x12\x17\n" +
	"\x04odds\x18\x02 \x01(\x03H\x01R\x04odds\x88\x01\x01B\n" +
	"\n" +
	"\b_roadNumB\a\n" +
	"\x05_oddsB\x1bZ\x19egame-grpc/game/common/pbb\x06proto3"

var (
	file_sjxj_proto_rawDescOnce sync.Once
	file_sjxj_proto_rawDescData []byte
)

func file_sjxj_proto_rawDescGZIP() []byte {
	file_sjxj_proto_rawDescOnce.Do(func() {
		file_sjxj_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sjxj_proto_rawDesc), len(file_sjxj_proto_rawDesc)))
	})
	return file_sjxj_proto_rawDescData
}

var file_sjxj_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sjxj_proto_goTypes = []any{
	(*Sjxj_BetOrderResponse)(nil), // 0: sjxj.sjxj_BetOrderResponse
	(*Sjxj_WinInfo)(nil),          // 1: sjxj.sjxj_WinInfo
	(*Sjxj_WinArr)(nil),           // 2: sjxj.sjxj_WinArr
}
var file_sjxj_proto_depIdxs = []int32{
	1, // 0: sjxj.sjxj_BetOrderResponse.winInfo:type_name -> sjxj.sjxj_WinInfo
	2, // 1: sjxj.sjxj_WinInfo.winArr:type_name -> sjxj.sjxj_WinArr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sjxj_proto_init() }
func file_sjxj_proto_init() {
	if File_sjxj_proto != nil {
		return
	}
	file_sjxj_proto_msgTypes[0].OneofWrappers = []any{}
	file_sjxj_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sjxj_proto_rawDesc), len(file_sjxj_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sjxj_proto_goTypes,
		DependencyIndexes: file_sjxj_proto_depIdxs,
		MessageInfos:      file_sjxj_proto_msgTypes,
	}.Build()
	File_sjxj_proto = out.File
	file_sjxj_proto_goTypes = nil
	file_sjxj_proto_depIdxs = nil
}
